<?php

use application\Session; ?>
<?php echo $this->menu; ?>

<div class="container">
    <!-- validation -->
    <div class="row-fluid">

        <div class="block-content collapse in">
            <div class="span12">
                <br />
                <div class="table-header">
                    Formulario
                    <a href="<?php echo URL . "generico/render/categoriaCientifica"; ?>" style="color: white;"><span class="muted pull-right">Voltar a tabela</span></a>
                </div>
                <!-- BEGIN FORM-->
                <form id="" class="form-horizontal" method="POST">
                    <fieldset>
                        <legend>Editar  Categoria Cientifica</legend>

                        <div class="group-control">
                            <label class="control-label">Nome<span class="required">*</span></label>
                            <div class="controls">

                                <input type="text" name="nome" data-required="1" class="form-control span6 m-wrap" value="<?php
                                if (isset($this->dados)): echo $this->dados->getNome();
                                endif;
                                ?>"/>
                            </div>
                        </div>
                    </fieldset>
                    <input name="enviar" type="hidden" value="1"/>
                    <input name="opcao" type="hidden" value="unidadeOrganica"/>
                    <label class="col-md-5 col-xs-4 control-label" for="buscar"></label>
                        <button type="submit" class="btn btn-primary" id="ediat">Editar</button>
                        <button type="reset" class="btn btn-danger   active">Cancelar</button>
                    </div>

                    <!-- END FORM-->
                </form>
            </div>
        </div>
    </div>







