<?php

use application\Session;

function selected($value, $selected) {
    return $value == $selected ? ' selected="selected"' : '';
}
?>
<div id="wrap">

    <!-- Header
    ================================================== -->
    <div id="nav-bar" class="">
        <div class="pull-left">
            <div id="header-container">

                <div class="dropdown">
                    <a class="header-dropdown dropdown-toggle accent-color" data-toggle="dropdown" href="#" style="color: white;">
                        <?php
                        if (isset($this->titulo)): echo $this->titulo;
                        endif;
                        ?>
                        <b class="caret"></b>
                    </a>

                </div>
            </div>
        </div>
        <div class="pull-right">
            <div id="top-info" class="pull-right">
                <!--                                <a id="settings" href="#" class="win-command pull-right">
                                                    <span class="win-commandicon win-commandring icon-cog-3"></span>
                                                </a>
                                <a id="logged-user" href="#" class="win-command pull-right">-->
                <span class="win-commandicon win-commandring icon-user"></span>
                </a>
                <div class="pull-left">
                    <h3><?php echo application\Session::get('nome'); ?></h3>
                    <a href="<?php echo URL . "login/logof"; ?>"><h4 class="text-warning pull-right">Sair</h4></a>
                </div>
            </div>
        </div>
    </div>


    <div class="metro panorama">
        <div class="panorama-sections">





            <div class="panorama-section">

                <h2>Usuarios</h2>


                <div class="tile-column-span-2">
                    <a class="tile wide imagetext wideimage bg-color-blue" href="<?php echo URL . "usuario" . DS1 . "index/" ?>">
                        <img src="<?php echo URL; ?>public/img/img3.png" alt="sam" style="width:200px;" />
                        <div class="textover-wrapper bg-color-blueDark">
                            <div class="text2">cadastrar, alterar, Apagar</div>
                        </div>
                    </a>


                </div>


                <h2>Categoria cientifica</h2>

                <div class="tile-column-span-2">


                    <a class="tile wide imagetext wideimage " href="<?php echo URL . "generico" . DS1 . "render/categoriaCientifica" ?>" style="background-color:white;">
                        <img src="<?php echo URL; ?>public/img/img10.png" alt="sam"  style="width:200px;"/>

                        <div class="textover-wrapper bg-color-blueDark">
                            <div class="text2">Cadastrar,Alterar,Apagar</div>
                        </div>
                    </a>

                </div>
            </div>


            <div class="panorama-section">



                <h2>Categoria do formador</h2>

                <div class="tile-column-span-2">


                    <a class="tile wide imagetext wideimage" href="<?php echo URL . "generico" . DS1 . "render/categoriaDocente/" ?>" style="background-color:white;">
                        <img src="<?php echo URL; ?>public/img/img10.png" alt="sam"  style="width:200px;"/>

                        <div class="textover-wrapper bg-color-red">
                            <div class="text2">Cadastrar,Alterar,Apagar</div>
                        </div>
                    </a>

                </div>


                <h2>Unidade organica</h2>

                <div class="tile-column-span-2">


                    <a class="tile wide imagetext wideimage" href="<?php echo URL . "generico" . DS1 . "render/unidadeOrganica/" ?>" style="background-color:white;">
                        <img src="<?php echo URL; ?>public/img/img10.png" alt="sam"  style="width:200px;"/>

                        <div class="textover-wrapper bg-color-blueDark">
                            <div class="text2">Cadastrar,Alterar,Apagar</div>
                        </div>
                    </a>

                </div>


            </div>

            <div class="panorama-section">

                <h2>Universidade</h2>

                <div class="tile-column-span-2">


                    <a class="tile wide imagetext wideimage " href="<?php echo URL . "generico" . DS1 . "render/universidade/" ?>" style="background-color:white;">
                        <img src="<?php echo URL; ?>public/img/img10.png" alt="sam"  style="width:200px;"/>

                        <div class="textover-wrapper bg-color-blueDark">
                            <div class="text2">Cadastrar,Alterar,Apagar</div>
                        </div>
                    </a>

                </div>


                <h2>Função</h2>

                <div class="tile-column-span-2">


                    <a class="tile wide imagetext wideimage" href="<?php echo URL . "generico" . DS1 . "render/funcao/" ?>" style="background-color:white;">
                        <img src="<?php echo URL; ?>public/img/img10.png" alt="sam"  style="width:200px;"/>

                        <div class="textover-wrapper bg-color-red">
                            <div class="text2">Cadastrar,Alterar,Apagar</div>
                        </div>
                    </a>

                </div>

            </div>



            <div class="panorama-section tile-span-4">
                <h2>Log do sistema</h2>


                <a class="tile wide imagetext bg-color-grayLight wideimage" href="<?php echo URL . "log" . DS1 . "index/" ?>">
                    <div class="image-wrapper">
                        <img src="<?php echo URL; ?>public/img/img4.png"   class="img-responsive img-rounded" />
                    </div>
                    <div class="column-text">
                        <div class="text4">Ver logs</div>
                    </div>
                </a>



            </div>




        </div>
    </div>
</div>
