<?php

use application\Session;

function selected($value, $selected) {
    return $value == $selected ? ' selected="selected"' : '';
}
?>





<aside id="sidebar" class="column">
    <hr/>
    <h3>Aluno</h3>
    <ul class="toggle">
        <li class="icn_categories"><a  href="<?php echo URL . "matricula" . DS1 . "index/" ?>" class="" rel="<?php echo URL . "matricula" . DS1 . "index/" ?>">Ver</a></li>
        <li class="icn_new_article"><a  href="<?php echo URL . "matricula" . DS1 . "adicionar/" ?>" class="" rel="<?php echo URL . "matricula" . DS1 . "adicionar/" ?>">Novo</a></li>
        <li class="icn_edit_article"><a href="<?php echo URL . "matricula" . DS1 . "editar/" ?>" class="" rel="<?php echo URL . "matricula" . DS1 . "editar/" ?>">Editar</a></li>
        <li class="icn_jump_back"><a   href="<?php echo URL . "matricula" . DS1 . "remover/" ?>" class="" rel="<?php echo URL . "matricula" . DS1 . "remover/" ?>">Apagar</a></li>
    </ul>
    <h3>Docente</h3>
    <ul class="toggle">
        <li class="icn_categories"><a   href="<?php echo URL . "docente" . DS1 . "index/" ?>" class="click" rel="<?php echo URL . "docente" . DS1 . "index/" ?>">Ver</a></li>
        <li class="icn_new_article"><a href="<?php echo URL . "docente" . DS1 . "adicionar/" ?>" class="click" rel="<?php echo URL . "docente" . DS1 . "adicionar/" ?>">Novo</a></li>
        <li class="icn_edit_article"><a href="<?php echo URL . "docente" . DS1 . "editar/" ?>" class="click" rel="<?php echo URL . "docente" . DS1 . "editar/" ?>">Editar</a></li>
        <li class="icn_jump_back"><a href="<?php echo URL . "docente" . DS1 . "remover/" ?>" class="click" rel="<?php echo URL . "docente" . DS1 . "remover/" ?>">Apagar</a></li>
    </ul>
    <h3>Curso</h3>
    <ul class="toggle">
        <li class="icn_categories"><a   href="<?php echo URL . "curso" . DS1 . "index/" ?>" class="click" rel="<?php echo URL . "curso" . DS1 . "index/" ?>">Ver</a></li>
        <li class="icn_new_article"><a href="<?php echo URL . "curso" . DS1 . "adicionar/" ?>" class="click" rel="<?php echo URL . "curso" . DS1 . "adicionar/" ?>">Novo</a></li>
        <li class="icn_edit_article"><a href="<?php echo URL . "curso" . DS1 . "editar/" ?>" class="click" rel="<?php echo URL . "curso" . DS1 . "editar/" ?>">Editar</a></li>
        <li class="icn_jump_back"><a href="<?php echo URL . "curso" . DS1 . "remover/" ?>" class="click" rel="<?php echo URL . "curso" . DS1 . "remover/" ?>">Apagar</a></li>
    </ul>

    <h3>Modúlo</h3>
    <ul class="toggle">
        <li class="icn_categories"><a   href="<?php echo URL . "modulo" . DS1 . "index/" ?>" class="click" rel="<?php echo URL . "modulo" . DS1 . "index/" ?>">Ver</a></li>
        <li class="icn_new_article"><a href="<?php echo URL . "modulo" . DS1 . "adicionar/" ?>" class="click" rel="<?php echo URL . "modulo" . DS1 . "adicionar/" ?>">Novo</a></li>
        <li class="icn_edit_article"><a href="<?php echo URL . "modulo" . DS1 . "editar/" ?>" class="click" rel="<?php echo URL . "modulo" . DS1 . "editar/" ?>">Editar</a></li>
        <!---
         <li class="icn_jump_back"><a href="#" class="click" rel="<?php //echo URL . "modulo" . DS1 . "remover/"            ?>">Apagar</a></li>
        ----->
    </ul>

    <h3>Nota</h3>
    <ul class="toggle">
        <li class="icn_categories"><a   href="<?php echo URL . "nota" . DS1 . "listar/" ?>" class="" rel="">Ver Notas</a></li>

        <li class="icn_categories"><a   href="<?php echo URL . "nota" . DS1 . "index/" ?>" class="" rel="">Lançar Nota</a></li>
        <li class="icn_edit_article"><a href="<?php echo URL . "nota" . DS1 . "editar/" ?>"  class=""rel="">Editar</a></li>
        <li class="icn_jump_back"><a href="<?php echo URL . "nota" . DS1 . "remover/" ?>" class=""rel="">Apagar</a></li>
    </ul>

    <h3>Programa</h3>
    <ul class="toggle">
        <li class="icn_categories"><a   href="<?php echo URL . "programa" . DS1 . "index/" ?>" class="click" rel="<?php echo URL . "programa" . DS1 . "index/" ?>">Ver</a></li>
        <li class="icn_new_article"><a href="<?php echo URL . "programa" . DS1 . "adicionar/" ?>" class="click" rel="<?php echo URL . "programa" . DS1 . "adicionar/" ?>">Novo</a></li>
        <li class="icn_edit_article"><a href="<?php echo URL . "programa" . DS1 . "editar/" ?>" class="click" rel="<?php echo URL . "programa" . DS1 . "editar/" ?>">Editar</a></li>
        <li class="icn_jump_back"><a href="<?php echo URL . "programa" . DS1 . "remover/" ?>" class="click" rel="<?php echo URL . "programa" . DS1 . "remover/" ?>">Apagar</a></li>
    </ul>

</ul>

<h3>Relatorio</h3>
<ul class="toggle">
    <li class="icn_categories"><a   href="<?php echo URL . "relatorio" . DS1 . "graficoGeral/" ?>" class="click" rel="<?php echo URL . "relatorio" . DS1 . "graficoGeral/" ?>">Grafico</a></li>
    <li class="icn_categories"><a   href="<?php echo URL . "relatorio" . DS1 . "index/" ?>" class="click" rel="<?php echo URL . "relatorio" . DS1 . "index/" ?>">Por Matricula</a></li>
    <li class="icn_categories"><a   href="<?php echo URL . "relatorio" . DS1 . "aproveitamentoGrafico/" ?>" class="click" rel="<?php echo URL . "relatorio" . DS1 . "aproveitamentoGrafico/" ?>">Por Aproveitamento</a></li>
</ul>

<h3>Diploma</h3>
<ul class="toggle">
    <li class="icn_categories"><a   href="<?php echo URL . "diploma" . DS1 . "index/" ?>" class="click" rel="<?php echo URL . "diploma" . DS1 . "index/" ?>">Ver</a></li>

</ul>


<h3>Admin</h3>
<ul class="toggle">
    <li class="icn_settings"><a href="<?php echo URL . "usuario" . DS1 . "index/" ?>" class="click" rel="<?php echo URL . "usuario" . DS1 . "index/" ?>">Usuarios</a></li>
    <li class="icn_jump_back"><a href="<?php echo URL . "login/logof"; ?>">Sair</a></li>
</ul>
</aside><!-- end of sidebar -->












<div id="wrap">

    <!-- Header
    ================================================== -->
    <div id="nav-bar" class="">
        <div class="pull-left">
            <div id="header-container">

                <div class="dropdown">
                    <a class="header-dropdown dropdown-toggle accent-color" data-toggle="dropdown" href="#" style="color: white;">
                        Painel de Administração
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="<?php echo URL . "matricula" . DS1 . "index/" ?>">Matriculas</a></li>
                        <li><a href="<?php echo URL . "docente" . DS1 . "index/" ?>">Docentes</a></li>
                        <li><a href="<?php echo URL . "curso" . DS1 . "index/" ?>">Cursos</a></li>
                        <li><a href="<?php echo URL . "modulo" . DS1 . "index/" ?>">Módulos</a></li>
                        <li><a href="<?php echo URL . "nota" . DS1 . "listar/" ?>">Notas</a></li>
                        <li><a href="<?php echo URL . "relatorio" . DS1 . "graficoGeral/" ?>">Relatório</a></li>
                        <li><a href="<?php echo URL . "diploma" . DS1 . "index/" ?>">Diplomas</a></li>
                        <li><a href="<?php echo URL . "certificado" . DS1 . "index/" ?>">Certificado</a></li>
                        <li><a href="<?php echo URL . "programa" . DS1 . "index/" ?>">Programa</a></li>
                        <li><a href="<?php echo URL . "usuario" . DS1 . "index/" ?>">Usuarios</a></li>
                        <li><a href="<?php echo URL . "login/logof"; ?>">Sair</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="pull-right" style="position: absolute; right: 210px;">
            <div id="top-info" class="pull-right">
                 <a id="logged-user" href="#" class="win-command pull-right">
                    <span class="win-commandicon win-commandring icon-user"></span>
                </a>
                <div class="pull-left">
                    <h3><?php echo application\Session::get('nome'); ?></h3>
                    <a href="<?php echo URL . "login/logof"; ?>"><h4 class="text-warning pull-right">Sair</h4></a>
                </div>
            </div>
        </div>
    </div>


    <div class="metro panorama">
        <div class="panorama-sections">

            <div class="panorama-section">

                <h2>Matriculas</h2>


                <div class="tile-column-span-2">
                    <a class="tile wide imagetext wideimage bg-color-blue" href="<?php echo URL . "matricula" . DS1 . "index/" ?>">
                        <img src="<?php echo URL; ?>public/img/img3.png" alt="sam" style="width:200px;" />
                        <div class="textover-wrapper bg-color-blueDark">
                            <div class="text2">Cadastrar, Alterar, DEletar, Alunos</div>
                        </div>
                    </a>
                    <h2>Cursos</h2>

                    <a class="tile wide imagetext wideimage bg-color-purple" href="<?php echo URL . "curso" . DS1 . "index/" ?>">
                        <img src="<?php echo URL; ?>public/img/img7.png" alt="sam" style="width:200px;" />
                        <div class="textover-wrapper bg-color-purple">
                            <div class="text2">Cadastrar, Alterar, DEletar, Alunos</div>
                        </div>
                    </a>
                    <h2>Módulos</h2>

                    <a class="tile wide imagetext wideimage bg-color-blue" href="<?php echo URL . "modulo" . DS1 . "index/" ?>">
                        <img src="<?php echo URL; ?>public/img/img8.png" alt="sam" style="width:200px;" />
                        <div class="textover-wrapper bg-color-blueDark">
                            <div class="text2">Cadastrar, Alterar, DEletar, Alunos</div>
                        </div>
                    </a>


                </div>



            </div>



            <div class="panorama-section">

                <h2>Docentes</h2>

                <div class="tile-column-span-2">


                    <a class="tile wide imagetext wideimage " href="<?php echo URL . "docente" . DS1 . "index/" ?>" style="background-color:white;">
                        <img src="<?php echo URL; ?>public/img/img6.png" alt="sam"  style="width:200px;"/>

                        <div class="textover-wrapper bg-color-blueDark">
                            <div class="text2">Cadastrar,Alterar,Deletar,Pesquisar</div>
                        </div>
                    </a>

                </div>


                <h2>Notas</h2>

                <div class="tile-column-span-2">


                    <a class="tile wide imagetext wideimage" href="<?php echo URL . "nota" . DS1 . "listar/" ?>" style="background-color:white;">
                        <img src="<?php echo URL; ?>public/img/img9.png" alt="sam"  style="width:200px;"/>

                        <div class="textover-wrapper bg-color-red">
                            <div class="text2">Cadastrar,Alterar,Deletar,Pesquisar</div>
                        </div>
                    </a>

                </div>


                <h2>Programa de Estudo</h2>

                <div class="tile-column-span-2">


                    <a class="tile wide imagetext wideimage" href="<?php echo URL . "programa" . DS1 . "index/" ?>" style="background-color:white;">
                        <img src="<?php echo URL; ?>public/img/img10.png" alt="sam"  style="width:200px;"/>

                        <div class="textover-wrapper bg-color-blueDark">
                            <div class="text2">Cadastrar,Alterar,Deletar,Pesquisar</div>
                        </div>
                    </a>

                </div>









            </div> 

            <div class="panorama-section tile-span-4">
                <h2>Documentos</h2>


                <a class="tile wide imagetext bg-color-grayLight" href="<?php echo URL . "relatorio" . DS1 . "graficoGeral/" ?>">
                    <div class="image-wrapper">
                        <img src="<?php echo URL; ?>public/img/img4.png" alt="sam"  class="img-responsive img-rounded" />
                    </div>
                    <div class="column-text">
                        <div class="text4">Imprima Relatorios</div>
                    </div>
                </a>







                <a class="tile app bg-color-blue" href="<?php echo URL . "certificado" . DS1 . "index/" ?>">
                    <div class="image-wrapper">
                        <img src="<?php echo URL; ?>public/img/img11.png" alt="sam"  style="width:400px"; height="400px;" />
                    </div>
                    <div class="column-text" style="color:black; fonte-size:14px;">
                        <div class="text4">Imprima Certificados</div>
                    </div>
                </a>


                <a class="tile wide imagetext bg-color-yellow" href="<?php echo URL . "diploma" . DS1 . "index/" ?>">
                    <div class="image-wrapper">
                        <img src="<?php echo URL; ?>public/img/img11.png" alt="sam"  style="width:400px"; height="400px;" />
                    </div>
                    <div class="column-text" style="color:black; fonte-size:14px;">
                        <div class="text4">Imprima Diplomas</div>
                    </div>
                </a>
               
                  <a class="tile  imagetext bg-color-blueDark" href="<?php echo URL . "usuario" . DS1 . "index/" ?>">
                       <h2>Usuarios</h2>
                       <img src="<?php echo URL; ?>public/img/5.jpg" alt="sam"  class="img-responsive img-circle" />
                      
                </a>






            </div>
           


        </div>
    </div>
</div>

