<?php echo $this->menu; ?>
<div class="" id="content" style="margin-left: 8px;">
    <!-- validation -->
    <div class="row-fluid">
        <!-- block -->
        <div class="block">

            <div class="col-12 pull-left" style="margin-left: 20px; margin-top:   -90px; display: block;">
                <!--<h4>Adicionar Novo</h4>-->
                <div class="navbar">
                    <ul class="nav navbar-nav">
                        <li class="active click"><a href="<?php echo URL . "generico" . DS1 . "adicionar/universidade" ?>" class="btn btn-primary"><span style="font-size: 14px; color: #FFFFFF;">Novo</span></a></li>
                    </ul>
                </div>


            </div>

            <div class="block-content collapse in" style="margin-top:1px;">
                <div class="span12">

                    <table  class="table table-striped table-bordered" id="tabela">   
                        <caption class="text-center text-big text-info">Tabela de universidades cadastradas</caption>
                        <thead>
                            <tr class="odd gradeA">
                                <th>Nome</th> 

                            </tr>
                        </thead>

                        <tbody>
                            <?php if (isset($this->dados) && !empty($this->dados)): ?>
                                <?php foreach ($this->dados as $dados): ?>

                                    <tr>
                                        <td><?php print $dados->getNome(); ?></td>
                                        <td><a rel="<?php print URL . "generico/editar/" . $dados->getId(); ?>/universidade" href="<?php print URL . "generico/editar/" . $dados->getId(); ?>/universidade" id="usuario1"><i class="glyphicon glyphicon-pencil" ></i></a></td>
                                        <td><a rel="<?php print URL . "generico/editar/" . $dados->getId(); ?>/universidade" href="<?php print URL . "generico/remover/" . $dados->getId(); ?>/universidade" id="remover"><i class="glyphicon glyphicon-trash" style="color: red;"></i></a></td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    <?php else: ?>
                        <h2 class="text-center text-error">Nenhum universidade cadastrada</h2>
                    <?php endif; ?>
                   
                </div>
            </div>
        </div>
        <!-- /block -->
    </div>
</div>