<?php echo $this->menu; ?>
<div class="span10 " id="content" style="margin-left: 150px;">
    <!-- validation -->
    <div class="row-fluid">
        <!-- block -->
        <div class="block">
            <div class="navbar navbar-inner block-header" style="margin-top: 20px;">
                <div class="muted pull-right"  style="padding: 10px; float: left; color: blue;"></div>
            </div>
            <div class="block-content collapse in">
                <div class="span12">
                    <!-- BEGIN FORM-->
                    <form id="adicionar" class="form-horizontal" method="POST" enctype="multipart/form-data">
                        <fieldset>
                            <legend>Adicionar nova universidade</legend>

                            <div class="group-control">
                                <label class="control-label">Nome<span class="required">*</span></label>
                                <div class="controls">

                                    <input type="text" name="nome" data-required="1" class="span6 m-wrap"/>
                                </div>
                            </div>
                        </fieldset>
                        <input name="enviar" type="hidden" value="1"/>
                        <input name="opcao" type="hidden" value="universidade"/>
                        <div class="form-actions">
                            <button type="submit" class="btn btn-primary" id="adicionar">Adicionar</button>
                            <button type="reset" class="btn">Cancelar</button>
                        </div>

                        <!-- END FORM-->
                    </form>
                </div>
            </div>
        </div>
        <!-- /block -->
    </div>
    <!-- /validation -->

</div>





