
<table  class="table table-striped table-bordered" id="tabela">  
    <caption class="text-big text-center ">
        <?php
        if (isset($this->titulo)): echo $this->titulo;
        endif;
        ?></caption>
    <thead>
        <tr class="odd gradeA">


            <th>Nª BI</th> 
            <th>Nome</th>
            <th>Grau</th>
            <th>Modulo</th>
            <th>Editar</th>

        </tr>
    </thead>

    <tbody>

        <?php if (isset($this->dados) && !empty($this->dados)): ?>
            <?php foreach ($this->dados as $dados): ?>
                <tr>
                    <td><?php print $dados['bi']; ?></td>
                    <td><a href="https://localhost/uan/docente/informacao/<?php echo $dados['docente']; ?>"><?php print $dados['nome']; ?></a></td>
                    <td><?php print $dados['grau']; ?></td>
                    <td><?php print $dados['nome_modulo']; ?></td>
                    <td><a href="#" id="remover" rel="<?php echo URL . "docente" . DS1 . "remover/" . $dados['pessoa']; ?>"><i class="glyphicon glyphicon-trash" style="color: orangered"></i></a></td>
                </tr>

                <?php
            endforeach;
        endif;
        ?>

    </tbody>
</table>

