<div class="" id="content" style="margin-left: 55px;">
    <!-- validation -->
    <div class="row-fluid">
        <br /><br /><br />
        <!-- block -->
        <div class="block">

            <h3 class="text-info text-big">  <?php
                if (isset($this->titulo)): echo $this->titulo;
                endif;
                ?> 
            </h3>
            <table  class="table table-striped table-bordered" id="tabela" cellspacing="0" width="100%">
                <caption class="text-big text-center ">
                    <?php
                    if (isset($this->titulo)): echo $this->titulo;
                    endif;
                    ?></caption>
                <thead>
                    <tr class="odd gradeA">


                        <th>Nª BI</th> 
                        <th>Nome</th>
                        <th>Grau</th>
                        <th>Modulo</th>
                        <th>Editar</th>

                    </tr>
                </thead>

                <tbody>

                    <?php if (isset($this->dados) && !empty($this->dados)): ?>
                        <?php foreach ($this->dados as $dados): ?>
                            <tr>
                                <td><?php print $dados['bi']; ?></td>
                                <td><a href="https://localhost/uan/docente/informacao/<?php echo $dados['docente']; ?>"><?php print $dados['nome']; ?></a></td>
                                <td><?php print $dados['grau']; ?></td>
                                <td><?php print $dados['nome_modulo']; ?></td>
                                <td><a href="<?php echo URL . "docente/editarDados/" . $dados['pessoa']; ?>" id="docente1" rel="<?php echo $dados['pessoa']; ?>"><i class="glyphicon glyphicon-pencil" style="color: orangered"></i></a></td>
                            </tr>

                            <?php
                        endforeach;
                    endif;
                    ?>

                </tbody>
            </table>
        </div>
    </div>
</div>

