<?php use application\Session; ?>
<div class="hr hr-18 dotted hr-double"></div>

<div class="container-fluid">
    <!-- validation -->
    <div class="row">
        <div class="clearfix">
            <div class="pull-right tableTools-container">

            </div>
        </div>

        <div class="table-header">
            <?php
            if (isset($this->titulo)): echo $this->titulo;
            endif;
            ?>
            <a href="<?php echo URL . "matricula"; ?>" style="color: white;"><span class="muted pull-right">Voltar a pesquisa</span></a>
        </div>


        <table  class="table table-striped table-bordered table-hover table-responsive" id="tabela">   
            <thead>
                <tr class="odd gradeA">


                    <th>Nª BI</th> 
                    <th> <i class="ace-icon fa fa-user bigger-110 hidden-480"></i>Nome</th>
                    <th><i class="ace-icon fa fa-times-circle-o bigger-110 hidden-480"></i>Grau</th>
                    <th><i class="ace-icon fa fa-paper-plane-o bigger-110 hidden-480"></i>Modulo</th>
                    <th></th>

                </tr>
            </thead>

            <tbody>

                <?php if (isset($this->dados) && !empty($this->dados)): ?>
                    <?php foreach ($this->dados as $dados): ?>
                        <tr>
                            <td><?php print $dados['bi']; ?></td>
                            <td><?php print $dados['nome']; ?></td>
                            <td><?php print $dados['grau']; ?></td>
                            <td><?php print $dados['nome_modulo']; ?></td>
                            <td>
                                <div class="hidden-sm hidden-xs action-buttons">

                                    <a class="blue" href="<?php print URL; ?>docente/informacao/<?php echo $dados['docente']; ?>">
                                        <i class="ace-icon fa fa-search-plus bigger-130"></i>
                                    </a>
                                    <a href="<?php echo URL . "docente/editarDados/" . $dados['pessoa']; ?>" id="editar1" rel="<?php echo $dados['aluno']; ?>" class="green">
                                        <span class="ace-icon fa fa-pencil bigger-130">

                                        </span>
                                    </a>
                                    <?php if (strcmp(Session::get('nivel'), 'gestor') == 0): ?> 
                                        <a href="#" id="remover" rel="<?php echo URL . "docente" . DS1 . "remover/" . $dados['pessoa']; ?>" class="red">
                                            <span class="ace-icon fa fa-trash-o bigger-130">

                                            </span>
                                        </a>
                                    <?php endif; ?>
                                </div>
                            </td>
                        </tr>

                        <?php
                    endforeach;
                endif;
                ?>

            </tbody>
        </table>


    </div>
</div>

