<div class="" id="content" style="margin-left: 55px;">
    <!-- validation -->
    <div class="row-fluid">
        <br /><br /><br />
        <!-- block -->
        <div class="block">

            <h3 class="text-info text-big">  <?php
                if (isset($this->titulo)): echo $this->titulo;
                endif;
                ?> 
            </h3>
            <table  class="table table-striped table-bordered" id="tabela" cellspacing="0" width="100%">   

                <thead>
                    <tr class="odd gradeA">


                        <th>Nª BI</th> 
                        <th>Nome</th>
                        <th>Grau</th>
                        <th>Modulo</th>

                    </tr>
                </thead>

                <tbody>

                    <?php if (isset($this->dados) && !empty($this->dados)): ?>
                        <?php foreach ($this->dados as $dados): ?>
                            <tr>
                                <td><?php print $dados['bi']; ?></td>
                                <td><a href="<?php print URL; ?>docente/informacao/<?php echo $dados['docente']; ?>"><?php print $dados['nome']; ?></a></td>
                                <td><?php print $dados['grau']; ?></td>
                                <td><?php print $dados['nome_modulo']; ?></td>
                            </tr>

                            <?php
                        endforeach;
                    endif;
                    ?>

                </tbody>
            </table>


        </div>
    </div>
</div>
