<?php echo $this->menu; ?>
<div class="" id="content" style="margin-left: 15px;">
    <!-- validation -->
    <div class="row-fluid">
        <!-- block -->
        <div class="block">



           <table  class="table table-striped table-bordered" id="tabela">  
               <caption class="text-big text-center text-danger">Log gerado pelo sistema</caption>
                <thead>
                    <tr class="odd gradeA">


                        <th>Ip da maquina</th>
                        <th>Acão</th>
                        <th>Data</th>
                        <th>Usuario</th>

                    </tr>
                </thead>

                <tbody>

                    <?php if (isset($this->dados) && !empty($this->dados)): ?>
                        <?php foreach ($this->dados as $dados): ?>
                            <tr>

                                <td><?php print $dados->getIpMaquina(); ?></td>
                                <?php if ($dados->getStatus() == 0): ?>
                                    <td class="alert-danger"><?php print $dados->getAcao(); ?></td>
                                <?php else: if ($dados->getStatus() == 1): ?>
                                        <td class="alert-success"><?php print $dados->getAcao(); ?></td>
                                    <?php else: ?>   
                                        <td class="alert-warning"><?php print $dados->getAcao(); ?></td>
                                    <?php endif; ?>
                                <?php endif; ?>



                                <td><?php print $dados->getData(); ?></td>
                                <td><?php print $dados->getUsuario()->getPessoa()->getNome(); ?></td>
                            </tr>

                            <?php
                        endforeach;
                    endif;
                    ?>

                </tbody>
            </table>
        </div>
    </div>
</div>



