<?php

use application\Session; ?>
<?php echo $this->menu; ?>



    <div class="hr hr-18 dotted hr-double"></div>

    <div class="container">
        <!-- validation -->
        <div class="row">
            <!--            <div class="clearfix">
                            <div class="pull-right tableTools-container">
            
                            </div>
                        </div>-->

            <div class="table-header">
                <?php
                if (isset($this->titulo)): echo $this->titulo;
                endif;
                ?>
                <a href="<?php echo URL.'nota/docente'; ?>" style="color: white;"><span class="muted pull-right">Voltar a pesquisa</span></a>
            </div>         
            <table  class="table table-striped table-bordered" id="tabela">   
                <caption>Notas Lançadas</caption>
                <thead>
                    <tr>

                        <th>Nome</th>
                        <th>Nota</th>

                    </tr>
                </thead>
<?php if (isset($this->dados) && !empty($this->dados)): ?>

                <tbody>
                    <?php foreach ($this->dados as $dados): ?>
                        <tr>
                            <td><?php print $dados['nome']; ?></td>

                            <?php if (isset($dados['nota']) && !empty($dados['nota'])): ?>

                                <td><?php echo $dados['nota']; ?></td>
                            <?php else: ?> 
                                <td>            
                                    <form action="<?php print URL; ?>nota/adicionarNotaDocente"   method="POST">            
                                        <select  id="nota" name="nota">
                                            <option>Seleccionar Nota...</option>
                                            <option value="Excelente">Excelente</option>
                                            <option value="Bom">Bom</option>
                                            <option value="Suficiente">Suficiente</option>
                                        </select>

                                        <input name="enviar" type="hidden" value="1"/>
                                        <input type="hidden" name="modulo" value="<?php echo $dados['modulo']; ?>" />
                                        <input type="hidden" name="aluno" value="<?php print $dados['id']; ?>"/>
                                        <input name="button" type="submit" class="input" id="button" value="Adicionar"/>
                                    </form>
                                <?php endif; ?>


                        </tr>

                        <?php
                    endforeach;
                endif;
                ?>

            </tbody>
        </table>
    </div>
</div>




