

<?php echo $this->menu; ?>
<div class="span11 " id="content" style="margin-left: 300px; " >
    <div class="row-fluid">
        <div class="block">

            <div class="col-12 pull-right">
                <h3>Acesso Rapido</h3>
                <div class="navbar">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo URL . "nota" . DS1 . "index/" ?>"><span style="font-size: 14px; color: black;">Lançar Nota</span></a></li>
                        <li class="active"><a href="<?php echo URL . "nota" . DS1 . "editar/" ?>"><span style="font-size: 14px; color: black;">Editar</span></a></li>
                        <li class="active"><a href="<?php echo URL . "nota" . DS1 . "remover/" ?>"><span style="font-size: 14px; color: black;">Apagar</span></a></li>
                    </ul>
                </div>


            </div>

            <table  class="table table-striped table-bordered" id="tabela">   
                <thead>

                    <tr class="odd gradeA">

                        <th>Nª BI</th> 
                        <th>Nome</th>
                        <th>Nota</th>
                        <th>Editar</th>
                    </tr>
                </thead>

                <tbody>

                    <?php if (isset($this->dados) && !empty($this->dados)): ?>
                        <?php foreach ($this->dados as $dados): ?>
                            <tr>
                                <td><?php print $dados->getAluno()->getPessoa()->getBi(); ?></td>
                                <td><?php print $dados->getAluno()->getPessoa()->getNome(); ?></td>
                                <td><?php echo $dados->getNota(); ?></td>
                                <td>            
                                    <form action="<?php print URL; ?>nota/editar"   method="POST">            
                                        <select  id="nota" name="nota">
                                            <option>Seleccionar Nota...</option>
                                            <option value="Excelente">Excelente</option>
                                            <option value="Bom">Bom</option>
                                            <option value="Suficiente">Suficiente</option>
                                        </select>

                                        <input name="enviar" type="hidden" value="1"/>
                                        <input type="hidden" name="id" value="<?php print $dados->getId(); ?>"/>
                                        <input name="button" type="submit" class="input" id="button" value="Editar"/>
                                    </form>
                                </td>
                            </tr>

                            <?php
                        endforeach;
                    endif;
                    ?>

                </tbody>
            </table>
        </div>
    </div>
</div>




