<?php

use application\Session; ?>       
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container-fluid">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <?php if (Session::get('nivel') == "administrador"): ?>
                <a class="brand" href="#">Painel de Administração</a>
            <?php endif; ?>

            <?php if (Session::get('nivel') == "docente"): ?>
                <a class="brand" href="#">Painel de Docente</a>
            <?php endif; ?>

            <?php if (Session::get('nivel') == "aluno"): ?>
                <a class="brand" href="#">Painel de Aluno</a>
<?php endif; ?>

            <div class="nav-collapse collapse">
                <ul class="nav pull-right">
                    <li class="dropdown">
                        <a href="#" role="button" class="dropdown-toggle" data-toggle="dropdown"> <i class="icon-user"></i> <?php print Session::get('nome'); ?> <i class="caret"></i>

                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a tabindex="-1" href="<?php echo URL . "matricula" . DS1 . "informacao/" . Session::get('id'); ?>">Perfil</a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a tabindex="-1" href="<?php print URL ?>login/logof">Sair</a>
                            </li>
                        </ul>
                    </li>
                </ul>

                <ul class="nav">
<?php if (Session::get('nivel') == "administrador"): ?>
                        <li class="active">
                            <a href="<?php print URL ?>dashboard">Dashboard</a>
                        </li>
                    <?php endif; ?>

<?php if (Session::get('nivel') == "docente"): ?>
                        <li class="active">
                            <a href="<?php print URL ?>dashboard/docente">Dashboard</a>
                        </li>
                    <?php endif; ?>

<?php if (Session::get('nivel') == "aluno"): ?>
                        <li class="active">
                            <a href="<?php print URL ?>dashboard/aluno">Dashboard</a>
                        </li>
                    <?php endif; ?>


                    <?php if (isset($_layoutParam["menu"])): ?>
    <?php for ($i = 0; $i < count($_layoutParam["menu"]); $i++): ?>
                            <?php (($item && $_layoutParam["menu"][$i]["id"] == $item) ? $item_style = "corrent" : $item_style = ""); ?> 

                            <li class="active" id="<?php print $item_style; ?>"><a href="<?php echo $_layoutParam["menu"][$i]["link"]; ?>"><i class="icon-chevron-right"></i> <?php echo $_layoutParam["menu"][$i]["titulo"]; ?></a></li>
                            <?php
                        endfor;
                    endif;
                    ?>

                </ul>
            </div>
        </div>
    </div>
</div>


<?php if (isset($this->dados) && !empty($this->dados)): ?>



    <div class="span10 " id="content" style="margin-left: 400px; margin-top: 80px;">
        <!-- validation -->
        <div class="row-fluid">
            <!-- block -->
            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left text-success">Notas Lançadas</div>
                </div>
                <div class="block-content collapse in">
                    <div class="span12">

                        <table  class="table table-striped table-bordered">   
                            <thead>
                                <tr>

                                    <th>Nome</th>
                                    <th>Nota</th>

                                </tr>
                            </thead>

                            <tbody>
    <?php foreach ($this->dados as $dados): ?>
                                    <tr>
                                        <td><?php print $dados['nome']; ?></td>

                                        <?php if (isset($dados['nota']) && !empty($dados['nota'])): ?>

                                            <td><?php echo $dados['nota']; ?></td>
        <?php else: ?> 
                                            <td>            
                                                <form action="<?php print URL; ?>nota/adicionar"   method="POST">            
                                                    <select  id="nota" name="nota">
                                                        <option>Seleccionar Nota...</option>
                                                        <option value="Excelente">Excelente</option>
                                                        <option value="Bom">Bom</option>
                                                        <option value="Suficiente">Suficiente</option>
                                                    </select>

                                                    <input name="enviar" type="hidden" value="1"/>
                                                    <input type="hidden" name="aluno" value="<?php print $dados['id']; ?>"/>
                                                    <input name="button" type="submit" class="input" id="button" value="Adicionar"/>
                                                </form>
                                            </td>


        <?php endif; ?>


                                    </tr>

                                    <?php
                                endforeach;
                            endif;
                            ?>

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>




