<?php echo $this->menu; ?>



<?php if (isset($this->dados) && !empty($this->dados)): ?>



    <div class="span10 " id="content" style="margin-left: 400px; margin-top: 80px;">
        <!-- validation -->
        <div class="row-fluid">
            <!-- block -->
            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left text-success">Notas Lançadas</div>
                </div>
                <div class="block-content collapse in">
                    <div class="span12">

                        <table  class="table table-striped table-bordered">   
                            <thead>
                                <tr>

                                    <th>Nome</th>
                                    <th>Nota</th>

                                </tr>
                            </thead>

                            <tbody>
    <?php foreach ($this->dados as $dados): ?>
                                    <tr>
                                        <td><?php print $dados['nome']; ?></td>

                                        <?php if (isset($dados['nota']) && !empty($dados['nota'])): ?>

                                            <td><?php echo $dados['nota']; ?></td>
        <?php else: ?> 
                                            <td>            
                                                <form action="<?php print URL; ?>nota/adicionar"   method="POST">            
                                                    <select  id="nota" name="nota">
                                                        <option>Seleccionar Nota...</option>
                                                        <option value="Excelente">Excelente</option>
                                                        <option value="Bom">Bom</option>
                                                        <option value="Suficiente">Suficiente</option>
                                                    </select>

                                                    <input name="enviar" type="hidden" value="1"/>
                                                    <input type="hidden" name="aluno" value="<?php print $dados['id']; ?>"/>
                                                    <input name="button" type="submit" class="input" id="button" value="Adicionar"/>
                                                </form>
                                            </td>


        <?php endif; ?>


                                    </tr>

                                    <?php
                                endforeach;
                            endif;
                            ?>

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>




