

<div class="hr hr-18 dotted hr-double"></div>

<div class="container">
    <!-- validation -->
    <div class="row">
        <!--            <div class="clearfix">
                        <div class="pull-right tableTools-container">
        
                        </div>
                    </div>-->

        <div class="table-header">
            <?php
            if (isset($this->titulo)): echo $this->titulo;
            endif;
            ?>
            <a href="<?php echo URL . "nota"; ?>" style="color: white;"><span class="muted pull-right">Voltar ao menu</span></a>
        </div>

        <table  class="table table-striped table-bordered table-hover table-responsive" id="tabela">  
            <thead>
                <tr>

                    <th>Nome</th>
                    <th>Nota</th>
                    <th></th>

                </tr>
            </thead>

            <tbody>
                <?php if (isset($this->dados) && !empty($this->dados)): ?>



                    <?php foreach ($this->dados as $dados): ?>
                        <tr>
                            <td><?php print $dados['nome']; ?></td>

                            <?php if (isset($dados['nota']) && !empty($dados['nota'])): ?>

                                <td>
                                    <?php
                                    if (strcmp($dados['nota'], 'Excelente') == 0):
                                        ?> 

                                        <span class="label label-lg label-success"> <?php echo $dados['nota']; ?></span>
                                        <?php
                                    endif;
                                    ?>

                                    <?php
                                    if (strcmp($dados['nota'], 'Bom') == 0):
                                        ?> 
                                        <span class="label label-lg label-warning"> <?php echo $dados['nota']; ?></span>
                                        <?php
                                    endif;
                                    ?>

                                    <?php
                                    if (strcmp($dados['nota'], 'Suficiente') == 0):
                                        ?> 
                                        <span class="label label-lg label-danger"> <?php echo $dados['nota']; ?></span>

                                        <?php
                                    endif;
                                    ?>


                                </td>
                            <?php else: ?>
                                <td>            
                                    <form action="<?php print URL; ?>nota/adicionar"   method="POST">            
                                        <select  id="nota" name="nota">
                                            <option>Seleccionar Nota...</option>
                                            <option value="Excelente">Excelente</option>
                                            <option value="Bom">Bom</option>
                                            <option value="Suficiente">Suficiente</option>
                                        </select>

                                        <input name="enviar" type="hidden" value="1"/>
                                        <input type="hidden" name="modulo" value="<?php echo $dados['modulo']; ?>" />
                                        <input type="hidden" name="aluno" value="<?php print $dados['id']; ?>"/>
                                        <button type="submit" class="btn btn-primary" id="button">Adicionar</button>
                                    </form>
                                </td>
                            <?php endif; ?>

                            <?php if (isset($dados['nota']) && !empty($dados['nota'])): ?>

                                <td>
                                    <div class="hidden-sm hidden-xs action-buttons">

                                        <a href="#" id="remover" rel="<?php echo URL . "nota" . DS1 . "remover/" . $dados['idnota']; ?>" class="red">
                                            <span class="ace-icon fa fa-trash-o bigger-130">

                                            </span>
                                        </a>
                                    </div>
                                </td>
                            <?php else: ?>
                                <td>
                                    <div class="hidden-sm hidden-xs action-buttons">

                                        <a href="#" id="remover" rel="<?php echo URL . "nota" . DS1 . "remover/" . $dados['idnota']; ?>" class="red hide">
                                            <span class="ace-icon fa fa-trash-o bigger-130">

                                            </span>
                                        </a>
                                    </div>
                                </td>

                            <?php endif; ?>


                            <?php
                        endforeach;
                    else:
                        ?>
                <p>Nenhum dado encontrado</p>
            <?php
            endif;
            ?>      





            </tr>



            </tbody>
        </table>
    </div>
</div>







