<?php echo $this->menu; ?>
<div class="span11 " id="content" style="margin-left: 300px; " >
    <div class="row-fluid">
        <div class="block">
            <table  class="table table-striped table-bordered" id="tabela">   
                <thead>

                    <tr class="odd gradeA">

                        <th>Nª BI</th> 
                        <th>Nome</th>
                        <th>Nota</th>
                        <th>Curso</th>
                        <th>Modúlo</th>
                    </tr>
                </thead>

                <tbody>

                    <?php if (isset($this->nota) && !empty($this->nota)): ?>
                        <?php foreach ($this->nota as $dados): ?>
                            <tr>
                                <td><?php print $dados['bi']; ?></td>
                                <td><?php print $dados['nome']; ?></td>
                                <td><?php print $dados['nota']; ?></td>
                                <td><?php print $dados['n1']; ?></td>
                                <td><?php print $dados['n2']; ?></td>
                            </tr>

                            <?php
                        endforeach;
                    endif;
                    ?>

                </tbody>
            </table>
        </div>
    </div>
</div>



