<?php echo $this->menu; ?>
<div class="span11 " id="content" style="margin-left: 300px; " >
    <div class="row-fluid">
        <div class="block">

            <div class="col-12 pull-right">
                <h3></h3>
                <div class="navbar">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo URL . "nota" . DS1 . "index/" ?>"><span style="font-size: 14px; color: black;">Lançar Nota</span></a></li>
                        <li class="active"><a href="<?php echo URL . "nota" . DS1 . "editar/" ?>"><span style="font-size: 14px; color: black;">Editar</span></a></li>
                        <li class="active"><a href="<?php echo URL . "nota" . DS1 . "remover/" ?>"><span style="font-size: 14px; color: black;">Apagar</span></a></li>
                    </ul>
                </div>


            </div>

            <div style="position:absolute;
                 top: 250px;
                 left: 600px;">

                <input type="number" name="ano" id="ano" data-required="1"  placeholder="Ano" maxlength="4"class="span2 m-wrap"/>
                <select id="curso" >
                    <option value="">- Curso -</option>

                </select>

                <select id="modulo">
                    <option value="">- Modulo -</option>

                </select>
                <input type="button" name="btnPesquisar" value="Pesquisar" class="buscar"  onclick="getDados('buscar');"/>
                <input type="button" name="btnPesquisar" value="Carregar Todos" class="buscar"  onclick="getTodos('buscar');" />
                <input type="hidden" value="<?php echo URL; ?>public/img/6.gif" id="img"/>

            </div>
            <h3 style="position: absolute; right: 600px;">  <?php
                if (isset($this->titulo)): echo $this->titulo;
                endif;
                ?> </h3>
            <div id="conteudo">

            </div>

        </div>
    </div>
</div>



