<?php

use application\Session; ?>
<?php echo $this->menu; ?>



<div class="container">



    <div class="row">
        <div class="col-xs-12">


            <form action="<?php print URL; ?>nota/pesquisarEditar" id="buscar" class="form-horizontal" method="POST"target="_BLANK" >
                <fieldset>
                    <legend class="text-info text-center">Selecciona os dados a pesquisar</legend>


                    <div class="form-group">
                        <label class="col-md-4 col-xs-4 control-label">Ano<span class="required">*</span></label>
                        <div class="col-md-3 col-xs-3">
                            <input type="number" name="ano" data-required="1" class="form-control input-md"/>

                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-4 col-xs-4 control-label">Curso<span class="required">*</span></label>
                        <div class="col-md-3 col-xs-3">
                            <select class="form-control" id="curso" name="curso">
                                <option value="000">-Selecciona um curso-</option>
                            </select>


                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-4 col-xs-4 control-label">Modúlo<span class="required">*</span></label>
                        <div class="col-md-3 col-xs-3">
                            <select class="form-control" id="modulo" name="modulo">
                                <option value="000">-Seleciona um modulo-</option>
                            </select>
                        </div>
                    </div>


                    <input name="enviar" type="hidden" value="1"/>
                    <label class="col-md-4 col-xs-4 control-label" for="buscar"></label>
                    <div class="col-md-3 col-xs-3">
                        <button type="submit" class="btn btn-primary" id="buscar">Procurar</button>
                        <button type="reset" class="btn btn-danger active">Cancelar</button>

                    </div>
                </fieldset>
            </form>
            <!-- END FORM-->
        </div>
    </div>
</div>


