<?php

use application\Session; ?>
<?php echo $this->menu; ?>
<div class="container">
    <!-- validation -->
    <br /><br /><br />
    <div class="row-fluid">

        <div class="block-content collapse in">
            <div class="span12">
                <br />
                <div class="table-header">
                   Informações de login
                </div>
                <!-- BEGIN FORM-->

                <table  class="table table-striped table-bordered">  
                       <thead>
                        <tr>
                            <th>Nome</th> 
                            <th>Login</th>
                            <th>Senha</th>
                            <th>Alterar</th>
                        </tr>
                    </thead>

                    <tbody>
                        <?php if (isset($this->dados) && !empty($this->dados)): $dados = $this->dados; ?>


                            <tr>
                                <td><?php print $dados->getPessoa()->getNome(); ?></td>
                                <td><?php print $dados->getLogin(); ?></td>
                                <td>*********</td>
                                <td><a href="<?php echo URL . "aluno/alteraSenha"; ?>">Alterar</a></td>
                            </tr>

                        </tbody>
                    </table>
                <?php else: ?>
                    <h2 class="text-center text-error">Dados não encontrado</h2>
                <?php endif; ?>

            </div>
        </div>
    </div>
</div>
