
<div class="span10 " id="content" style="margin-left: 200px;">
    <!-- validation -->
    <div class="row-fluid">
        <!-- block -->
        <div class="block">
          
            <div class="block-content collapse in">
                <div class="span12">
                    <!-- BEGIN FORM-->
                    <form action="<?php print URL; ?>aluno/pesquisaPor" id="buscar" class="form-horizontal" method="POST" >
                        <fieldset>
                            <legend class="text-info" style="margin-left: 180px;">Selecciona os dados a pesquisar</legend>
                            <div class="control-group">
                                <label class="control-label">Curso<span class="required">*</span></label>
                                <div class="controls">
                                    <select class="span6 m-wrap " id="curso" name="curso">
                                        <option value="000">-Selecciona um curso-</option>
                                    </select>


                                </div>
                            </div>

                            <div class="control-group">
                                <label class="control-label">Modúlo<span class="required">*</span></label>
                                <div class="controls">
                                    <select class="span6 m-wrap" id="modulo" name="modulo">
                                        <option value="000">-Seleciona um modulo-</option>
                                    </select>


                                </div>
                            </div>
                        </fieldset>

                        <input name="enviar" type="hidden" value="1"/>
                        <div class="form-actions">
                            <button type="submit" class="btn btn-primary" id="buscar">Procurar</button>
                            <button type="reset" class="btn">Cancelar</button>
                        </div>
                    </form>
                    <!-- END FORM-->
                </div>
            </div>
        </div>
        <!-- /block -->
    </div>
    <!-- /validation -->

</div>




<br />

<?php if (isset($this->dados) && !empty($this->dados)): ?>



    <div class="span10 " id="content" style="margin-left: 300px;">
        <!-- validation -->
        <div class="row-fluid">
            <!-- block -->
            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left text-success">Dados Encontrados</div>
                </div>
                <div class="block-content collapse in">
                    <div class="span12">

                        <table  class="table table-striped table-bordered">   
                            <thead>
                                <tr>

                                    <th>CURSO</th> 
                                    <th>MODÚLO</th>
                                    <th>DOCENTE</th>
                                    <th>NOME</th>
                                    <th>DATA</th>

                                </tr>
                            </thead>

                            <tbody>

                                <?php if (isset($this->dados) && !empty($this->dados)): ?>
                                    <?php foreach ($this->dados as $dados): ?>
                                        <tr>
                                            <td><?php print $dados->getCurso()->getNome(); ?></td>
                                            <td><?php print $dados->getModulo()->getNome(); ?></td>
                                            <td><?php print $dados->getDocente()->getPessoa()->getNome(); ?></td>
                                            <td><?php print "{" . $dados->getNome() . "}"; ?><a href="<?php print URL . $dados->getNome(); ?>" target="_BLANK">     (VER)</a></td>
                                            <td><?php print $dados->getData(); ?></td>
                                        </tr>

                                        <?php
                                    endforeach;
                                endif;
                                ?>

                            </tbody>
                        </table>



                    </div>
                </div>
            </div>
        </div>
    </div>

<?php endif; ?>


