<?php

use application\Session; ?>
<?php echo $this->menu; ?>
<br /><br />
<div class="container">
    <!-- validation -->
    <div class="row-fluid">

        <div class="block-content collapse in">
            <div class="span12">
                <br />
                <div class="table-header">
                    Notas lançadas
                </div>
                <!-- BEGIN FORM-->

                <table  class="table table-striped table-bordered" style="margin-top: 50px;">   
                    <thead>
                        <tr>

                            <th>CURSO</th>
                            <th>MODÚLO</th>
                            <th>NOTA</th>
                            <th>DATA</th>

                        </tr>
                    </thead>

                    <tbody>

                        <?php if (isset($this->dados) && !empty($this->dados)): ?>
                            <?php foreach ($this->dados as $dados): ?>
                                <tr>
                                    <td><?php print $dados->getModulo()->getCurso()->getNome(); ?></td>
                                    <td><?php print $dados->getModulo()->getNome(); ?></td>
                                    <td><?php print $dados->getNota(); ?></td>
                                    <td><?php print date("d/m/Y", strtotime($dados->getData())); ?></td>
                                </tr>
                            <?php endforeach; ?>
                        <?php else: ?>
                    <p>Nenhuma nota lançada</p>


                        <?php endif; ?>


                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>


