<?php

use application\Session; ?>
<?php echo $this->menu; ?>
<div class="container">
    <!-- validation -->
    <div class="row-fluid">

        <div class="block-content collapse in">
            <div class="span12">
                <br />
                <div class="table-header">
                    Formulario de alteração da senha
                              </div>
                <!-- BEGIN FORM-->
                <form action="<?php print URL; ?>aluno/alteraSenha" id="editar" class="form form-horizontal" method="POST">
                    <fieldset>
                        <legend>Alterar senha</legend>


                        <div class="form-group">
                            <label class="col-xs-2 col-md-4 control-label">Senha<span class="required">*</span></label>

                            <input type="password" name="senha" data-required="1"  class="form-control span4 active"  id="senha"/>

                        </div>

                    </fieldset>
                    <input name="enviar" type="hidden" value="1"/>
                     <label class="col-md-5 col-xs-4 control-label" for="buscar"></label>
                        <button type="submit" class="btn btn-primary" id="editar">Editar</button>
                        <button type="reset" class="btn btn-danger active">Cancelar</button>
                    </div>

                    <!-- END FORM-->
            </div>
        </div>
    </div>
</div>

























</form>
<!-- END FORM-->
</div>
</div>
</div>
<!-- /block -->
</div>
<!-- /validation -->

</div>
</div>