
<?php echo $this->menu; ?>
<?php

use application\Session ?>

<style>

    .container {
        margin-top: 25px;
    }
    .form-inline .form-group > div.col-xs-8 {
        padding-left: 0;
        padding-right: 0;
    }
    .form-inline label {
        line-height: 34px;
    }
    .form-inline .form-control {
        width: 100%;
    }
    @media (min-width: 768px) {
        .form-inline .form-group {
            margin-bottom: 15px;
        }
    }

    .verifica{
        padding:3px;
        font-size:18px;
        border:3px #CCC solid;
    }

    .borda{
        border: 3px #CCC solid;
    }
    .texto{
        color: red;
        font-size: 13px;
    }

</style>


<div class="col-12 pull-left" style="position: absolute; top: -10px; left: 10px;">

    <p></p>
    <div class="navbar-nav">
        <ul class="nav navbar-nav">
            <li class="active"><a href="<?php echo URL . "docente" . DS1 . "index/" ?>" class="btn btn-primary"><span style="font-size: 14px; color:  #ffffff;" >Ver </span></a></li>
            <li class="active"><a href="<?php echo URL . "docente" . DS1 . "editar/" ?>" class="btn btn-primary"><span style="font-size: 14px; color: #ffffff;">Editar</span></a></li>
            <?php if (strcmp(Session::get('nivel'), 'gestor') == 0): ?>
                <li class="active"><a href="<?php echo URL . "docente" . DS1 . "remover/" ?>" class="btn btn-primary"><span style="font-size: 14px; color: #ffffff;">Apagar</span></a></li>
            <?php endif; ?>
        </ul>
    </div>


</div>
<div class="span10 " id="content" style="margin-left: 420px; ">
    <!-- validation -->
    <div class="row-fluid">
        <!-- block -->
        <br />
        <div class="block">

            <div class="navbar navbar-inner block-header">
                <div class="muted pull-right">Cadastrar em novo curso</div>
            </div>
            <div class="block-content collapse in">
                <div class="span12">
                    <!-- BEGIN FORM-->
                    <form action=""  class="form-horizontal" method="POST">

                        <legend>Curso a lecionar</legend>
                        <div class="form-group">
                            <label class="col-xs-2 control-label">Curso</label>

                            <select class="form-control span6 m-wrap borda" id="curso" name="curso">
                                <option value="">Selecciona um curso</option>
                            </select>
                        </div>
                        <div class="carregando"></div>
                        <div class="form-group">
                            <label class="col-xs-2 control-label">Modúlo<span class="required">*</span></label>
                            <select class="form-control  span6 m-wrap borda" id="modulo" name="modulo" >

                            </select>

                        </div>


                        <input name="enviar" type="hidden" value="1"/>
                        <div class="form-actions span10 text-center">
                            <button type="submit" class="btn btn-primary" id="adicionar">Salvar Dados</button>
                            <button type="reset" class="btn btn-danger   active">Cancelar</button>
                        </div>


                    </form>

                    <!-- END FORM-->
                </div>
            </div>
        </div>
        <!-- /block -->
    </div>
    <!-- /validation -->

</div>

