<?php echo $this->menu; ?>
<div class="" id="content" style="margin-left: 220px;">
    <!-- validation -->
    <div class="row-fluid">
        <!-- block -->
        <div class="block">
            <div class="col-12 pull-right">
                <h3>Acesso Rapido</h3>
                <div class="navbar">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo URL . "docente" . DS1 . "adicionar/" ?>"><span style="font-size: 14px; color: black;">Novo</span></a></li>
                        <li class="active"><a href="<?php echo URL . "docente" . DS1 . "editar/" ?>"><span style="font-size: 14px; color: black;">Editar</span></a></li>
                        <li class="active"><a href="<?php echo URL . "docente" . DS1 . "remover/" ?>"><span style="font-size: 14px; color: black;">Apagar</span></a></li>
                    </ul>
                </div>


            </div>

            <div style="position:absolute;
                 top: 250px;
                 left: 550px;">

                <select id="curso" >
                    <option value="">- Curso -</option>

                </select>
            </div>
            <table  class="table table-striped table-bordered" id="tabela">   
                <thead>
                    <tr class="odd gradeA">

                        <th>Nª BI</th> 
                        <th>Nome</th>
                        <th>Grau</th>
                        <th>Editar</th>
                    </tr>
                </thead>

                <tbody>

                    <?php if (isset($this->dados) && !empty($this->dados)): ?>
                        <?php foreach ($this->dados as $dados): ?>
                            <tr>
                                <td><?php print $dados->getPessoa()->getBi(); ?></td>
                                <td><?php print $dados->getPessoa()->getNome(); ?></td>
                                <td><?php print $dados->getGrau(); ?></td>
                                <td><a href="<?php echo URL . "docente/editarDados/" . $dados->getPessoa()->getId(); ?>" id="docente1" rel="<?php echo $dados->getPessoa()->getId(); ?>"><i class="icon-edit"></i></a></td>
                                        <?php
                                    endforeach;
                                endif;
                                ?>

                </tbody>
            </table>
        </div>
    </div>
</div>



