
<div class="control-group pull-right">
    <div class="controls">
        <select class="span6 m-wrap" name="genero">
            <option value="000">-Buscar Por-</option>
            <option value="Masculino">ABERTO</option>
            <option value="Femenino">CONFIRMADO</option>
        </select>                                    
    </div>
</div>
<br />
<table  class="table table-striped table-bordered">   
    <thead>
        <tr>

            <th>Nª BI</th> 
            <th>Nome</th>
            <th>Grau</th>
        </tr>
    </thead>

    <tbody>

        <?php if (isset($this->dados) && !empty($this->dados)): ?>
            <?php foreach ($this->dados as $dados): ?>
                <tr>
                    <td><?php print $dados->getPessoa()->getBi(); ?></td>
                    <td><?php print $dados->getPessoa()->getNome(); ?></td>
                    <td><?php print $dados->getGrau(); ?></td>
                </tr>

                <?php
            endforeach;
        endif;
        ?>

    </tbody>
</table>



