<?php echo $this->menu;?>
<div class=" " id="content" style="margin-left: 220px;">
    <!-- validation -->
    <div class="row-fluid">
        <!-- block -->
        <div class="block"><table  class="table table-striped table-bordered" id="tabela">   
                <thead>
                   <tr class="odd gradeA">


                        <th>Nª BI</th> 
                        <th>Nome</th>
                        <th>Grau</th>
                        <th>Curso</th>
                        <th>Modulo</th>
                    </tr>
                </thead>

                <tbody>

                    <?php if (isset($this->dados) && !empty($this->dados)): ?>
                        <?php foreach ($this->dados as $dados): ?>
                            <tr>
                                <td><?php print $dados->getPessoa()->getBi(); ?></td>
                                <td><?php print $dados->getPessoa()->getNome(); ?></td>
                                <td><?php print $dados->getGrau(); ?></td>
                                <td><?php print $dados->getModulo()->getCurso()->getNome(); ?></td>
                                <td><?php print $dados->getModulo()->getNome(); ?></td>
                            </tr>

                            <?php
                        endforeach;
                    endif;
                    ?>

                </tbody>
            </table>
        </div>
    </div>
</div>



