




<?php echo $this->menu; ?>


<div class="col-12 pull-left" style="position: absolute; top: -10px; left: 10px;">

    <h3></h3>
    <div class="navbar">
        <ul class="nav navbar-nav">
            <li class="active"><a href="<?php echo URL . "docente" . DS1 . "addCurso/" . $this->dados->getId(); ?>" class="btn btn-primary"><span style="font-size: 14px; color:  #ffffff;" >Adicionar novo curso</span></a></li>
            <li class="active"><a href="<?php echo URL . "docente" . DS1 . "index/" ?>" class="btn btn-primary"><span style="font-size: 14px; color:  #ffffff;" >Ver</span></a></li>

        </ul>
    </div>


</div>
<div class="container alert_info">    
    <div class="row" style="text-align:center; border-bottom:1px dashed #ccc;  padding:0 0 20px 0; margin-bottom:30px;">
        <br /><br /><br />
        <h3 style="font-family:arial; font-weight:bold; font-size:30px; padding-left: 30px;" class="text-left">
            Ficha do Formando
        </h3>

    </div>

    <?php if (isset($this->dados) && !empty($this->dados)): ?>

        <ul class="navbar navbar-default">
            <?php if (!empty($this->dados->getPessoa()->getImagem())) : ?>
                <li class="col-lg-3 col-md-2 col-sm-3 col-xs-4">
                    <img src="<?php print URL . DS1; ?><?php echo $this->dados->getPessoa()->getImagem(); ?>" class="img-responsive" alt="Imagem do Aluno" width="300px;">
                </li>
            <?php else: ?>                <li>
                <li class="col-lg-2 col-md-2 col-sm-3 col-xs-4">
                    <img src="<?php print URL; ?>public/img/10.jpg" class="img-responsive" alt="Imagem do Aluno">
                    <p>Descrição: imagem(largura:348,altura:348)</p>
                </li>
                <form id="guarda" method="POST" action="<?php print URL . "docente/editarImagem/"; ?>" accept-charset="utf-8" enctype="multipart/form-data">
                    <input type="file" name="imagem" />
                    <input type="hidden" name="id" value="<?php echo   $this->dados->getPessoa()->getId(); ?>" />
                     <input type="hidden" name="docente" value="<?php echo   $this->dados->getId(); ?>" />
                    <button type="submit" id="guarda" class="btn btn-info">Guardar</button>
                </form>

            <?php endif; ?>
        </ul>             
    </div> 

    <div style="position: absolute; left: 800px; top: 200px;">

        <span class="text-center">

            <h4>Nome: <?php echo ucfirst($this->dados->getPessoa()->getNome()); ?></h4>
            <h4>BI: <?php echo $this->dados->getPessoa()->getBi(); ?></h4>
            <h4>Genero: <?php echo ucfirst($this->dados->getPessoa()->getGenero()); ?></h4>
            <h4>Email: <?php echo $this->dados->getPessoa()->getEmail(); ?></h4>
            <h4>Telefone: <?php echo $this->dados->getPessoa()->getTelefone(); ?></h4>
            <h4>Nacionalidade: <?php echo ucfirst($this->dados->getPessoa()->getNacionalidade()); ?></h4>
            <h4>Grau: <?php echo ucfirst($this->dados->getGrau()); ?></h4>
            <hr>
        </span> 
        <br />
        <hr>
    </div>

    <span class="text-left">
        <?php if (isset($this->modulo) && !empty($this->modulo)): ?>


            <table  class="table table-striped table-bordered" >   
                <thead>
                <legend>Lecionando em</legend>
                <tr>

                    <th>Curso</th> 
                    <th>Modulo</th>


                </tr>
                </thead>

                <tbody>

                    <?php foreach ($this->modulo as $valor): ?>

                        <tr>

                            <td>
                                <?php echo $valor->getModulo()->getCurso()->getNome(); ?>


                            </td>

                            <td>
                                <?php echo $valor->getModulo()->getNome(); ?>
                            </td>


                        <?php endforeach; ?>
                    </tr>
                </tbody>
            </table>

            <?php
        endif;
        ?>


    </span>




<?php else: ?>
    <span class="text-center">

        <h2>SEM INFORMAÇÕES PARA MOSTRAR</h2>

        <hr>
    </span> 

<?php endif; ?>

