<style>
    /*Copied from bootstrap */
    .btn {
        display: inline-block;
        padding: 6px 12px;
        margin-bottom: 0;
        font-size: 14px;
        font-weight: normal;
        line-height: 1.42857143;
        text-align: center;
        white-space: nowrap;
        vertical-align: middle;
        cursor: pointer;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
        background-image: none;
        border: 1px solid transparent;
        border-radius: 4px;
    }
    /*Also */
    .btn-success {
        color: #fff;
        background-color: #5cb85c;
        border-color: #4cae4c;
    }
    /* This is copied from https://github.com/blueimp/jQuery-File-Upload/blob/master/css/jquery.fileupload.css */
    .fileinput-button {
        position: relative;
        overflow: hidden;
    }
    /*Also*/
    .fileinput-button input {
        position: absolute;
        top: 0;
        right: 0;
        margin: 0;
        opacity: 0;
        -ms-filter:'alpha(opacity=0)';
        font-size: 200px;
        direction: ltr;
        cursor: pointer;
    }

</style>






<?php echo $this->menu; ?>


<div class="container">
    <div class="row">

        <?php if (isset($this->dados) && !empty($this->dados)): ?>

            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad" >


                <div class="panel panel-info">
                    <div class="panel-heading">
                        <h3 class="panel-title"><?php echo ucfirst($this->dados->getPessoa()->getNome()) . ' ' . ucfirst($this->dados->getPessoa()->getApelido()); ?></h3>
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-3 col-lg-3 " align="center"> 
                                <?php if (!empty($this->dados->getPessoa()->getImagem())) : ?>
                                    <img alt="imagem" src="
                                         <?php print URL . $this->dados->getPessoa()->getImagem(); ?>" class="img img-circle img-responsive" />
                                     <?php else: ?>   
                                    <img src="<?php print URL; ?>public/img/10.jpg" class="img-responsive"/>

                                    <form id="guarda" method="POST" action="<?php print URL . "docente/editarImagem/" . $this->dados->getPessoa()->getId() ?>" accept-charset="utf-8" enctype="multipart/form-data" class="form-horizontal">
                                        <span class="fa fa-image fileinput-button">
                                            <span>escolha </span>
                                            <input type="file" name="imagem"/>
                                        </span>
                                        <input type="hidden" name="id" value="<?php echo $this->dados->getPessoa()->getId(); ?>" />
                                        <input type="hidden" name="docente" value="<?php echo $this->dados->getId(); ?>" />
                                        <button type="submit" id="guarda" class="btn btn-info">Guardar</button>
                                    </form>
                                <?php endif; ?>



                            </div>


                            <div class=" col-md-9 col-lg-9 "> 
                                <table class="table table-user-information">
                                    <tbody>
                                        <tr>
                                            <td>Nº do documento:</td>
                                            <td><?php echo $this->dados->getPessoa()->getBi(); ?></td>
                                        </tr>
                                        <tr>
                                            <td>Genero:</td>
                                            <td><?php echo ucfirst($this->dados->getPessoa()->getGenero()); ?></td>
                                        </tr>
                                        <tr>
                                            <td>Nacionalidade</td>
                                            <td><?php echo ucfirst($this->dados->getPessoa()->getNacionalidade()); ?></td>
                                        </tr>

                                        <tr>
                                        <tr>
                                            <td>Grau</td>
                                            <td><?php echo ucfirst($this->dados->getGrau()); ?></td>
                                        </tr>
                                        <tr>
                                            <td>Email</td>
                                            <td><a href="mailto:<?php echo $this->dados->getPessoa()->getEmail(); ?>"><?php echo $this->dados->getPessoa()->getEmail(); ?></a></td>
                                        </tr>
                                    <td class="red">Modulos a lecionar</td>
                                    <td>
                                        <?php foreach ($this->modulo as $valor): ?>

                                            <br />
                                            <?php echo $valor->getModulo()->getCurso()->getNome(); ?>(<?php echo $valor->getModulo()->getNome(); ?>)
                                            <br />
                                        <?php endforeach; ?>

                                    </td>

                                    </tr>

                                    </tbody>
                                </table>

                                <a href="<?php echo URL . "docente" . DS1 . "addCurso/" . $this->dados->getId(); ?>" class="btn btn-primary">Inscrever em curso</i></a>
                                <a href="https://localhost/uan/docente/pesquisaPor/$" class="btn btn-warning">Volta a lista</a>
                            </div>
                        </div>
                    </div>
                    <div class="panel-footer">
                        <a href="mailto:<?php echo $this->dados->getPessoa()->getEmail(); ?>" data-original-title="Enviar email" data-toggle="tooltip" type="button" class="btn btn-sm btn-primary"><i class="glyphicon glyphicon-envelope"></i></a>
                        <span class="pull-right">
                            <a href="<?php echo URL . "docente/editarDados/" . $this->dados->getId() . "/" . $this->dados->getAluno()->getId(); ?>" data-original-title="Editar este formando" data-toggle="tooltip" type="button" class="btn btn-sm btn-warning"><i class="glyphicon glyphicon-edit"></i></a>
                            <a id="remover" rel="<?php echo URL . "docente" . DS1 . "remover/" . $this->dados->getAluno()->getPessoa()->getId(); ?>" data-original-title="Remove formando" data-toggle="tooltip" type="button" class="btn btn-sm btn-danger"><i class="glyphicon glyphicon-remove"></i></a>
                        </span>
                    </div>

                </div>
            </div>
        <?php else: ?>
            <span class="text-center">

                <h2>SEM INFORMAÇÕES PARA MOSTRAR</h2>

            </span> 

        <?php endif; ?>
    </div>
</div>

















