<?php echo $this->menu;?>
<div class="span10 " id="content" style="margin-left: 420px;">
    <!-- validation -->
    <div class="row-fluid">
        <!-- block -->
        <div class="block">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-right">Dados do Docente</div>
            </div>
            <div class="block-content collapse in">
                <div class="span12">
                    <!-- BEGIN FORM-->
                    <form action="<?php print URL; ?>docente/adicionar" id="adicionar" class="form-horizontal" method="POST">
                        <fieldset>
                            <legend>Dados Pessoas</legend>
                            <div class="control-group">
                                <label class="control-label">Nome<span class="required">*</span></label>
                                <div class="controls">
                                    <input type="text" name="nome" data-required="1" class="span6 m-wrap"/>
                                </div>
                            </div>

                            <div class="control-group">
                                <label class="control-label">Apelido<span class="required">*</span></label>
                                <div class="controls">
                                    <input type="text" name="nome1" data-required="1" class="span6 m-wrap"/>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">Genero<span class="required">*</span></label>
                                <div class="controls">
                                    <select class="span6 m-wrap" name="genero">
                                        <option value="000">-Seleciona um genero-</option>
                                        <option value="Masculino">Masculino</option>
                                        <option value="Femenino">Femenino</option>
                                    </select>                                    
                                </div>
                            </div>

                            <div class="control-group">
                                <label class="control-label">Nª Bi<span class="required">*</span></label>
                                <div class="controls">
                                    <input name="bi" type="text" class="span6 m-wrap" maxlength="14"/>
                                </div>
                            </div>

                            <div class="control-group">
                                <label class="control-label">Nacionalidade<span class="required">*</span></label>
                                <div class="controls">
                                    <input name="nacionalidade" id="telefone" type="text" class="span6 m-wrap"/>
                                </div>
                            </div>

                            <div class="control-group">
                                <label class="control-label">Telefone<span class="required">*</span></label>
                                <div class="controls">
                                    <input name="telefone" type="tel" class="span6 m-wrap" maxlength="9"/>
                                </div>
                            </div>

                            <div class="control-group">
                                <label class="control-label">Email<span class="required">*</span></label>
                                <div class="controls">
                                    <input name="email"  class="span6 m-wrap" type="email" />
                                </div>
                            </div>


                            <div class="control-group">
                                <label class="control-label">Grau<span class="required">*</span></label>
                                <div class="controls">
                                    <select class="span6 m-wrap" name="grau">
                                        <option value="000">-Seleciona um grau-</option>
                                        <option value="Licenciado">Licenciado</option>
                                        <option value="Mestre">Mestre</option>
                                        <option value="Doctor">Doctor</option>
                                    </select>                                    
                                </div>
                            </div>

                            <fieldset>
                                <legend>Curso a Lecionar</legend>
                                <div class="control-group">
                                    <label class="control-label">Curso<span class="required">*</span></label>
                                    <div class="controls">
                                        <select class="span6 m-wrap" id="curso" name="curso">
                                            <option value=""></option>
                                        </select>


                                    </div>
                                </div>
                                <div class="carregando"></div>
                                <div class="control-group">
                                    <label class="control-label">Modúlo<span class="required">*</span></label>
                                    <div class="controls">
                                        <select class="span6 m-wrap" id="modulo" name="modulo">

                                        </select>


                                    </div>
                                </div>
                            </fieldset>



                        </fieldset>
                        <input name="enviar" type="hidden" value="1"/>
                        <div class="form-actions">
                            <button type="submit" class="btn btn-primary" id="adicionar">Salvar Dados</button>
                            <button type="reset" class="btn">Cancelar</button>
                        </div>

                        <!-- END FORM-->
                </div>
            </div>
        </div>
        <!-- /block -->
    </div>
    <!-- /validation -->

</div>






























</form>
<!-- END FORM-->
</div>
</div>
</div>
<!-- /block -->
</div>
<!-- /validation -->

</div>
</div>