<?php echo $this->menu;?>
<div class=" " id="content" style="margin-left: 220px;">
    <!-- validation -->
    <div class="row-fluid">
        <!-- block -->
        <div class="block">
            <table  class="table table-striped table-bordered" id="tabela">   
                <thead>
                    <tr class="odd gradeA">

                        <th>Nª BI</th> 
                        <th>Nome</th>
                        <th>Grau</th>
                         <th>Apagar</th>
                    </tr>
                </thead>

                <tbody>

                    <?php if (isset($this->dados) && !empty($this->dados)): ?>
                        <?php foreach ($this->dados as $dados): ?>
                            <tr>
                                <td><?php print $dados->getPessoa()->getBi(); ?></td>
                                <td><?php print $dados->getPessoa()->getNome(); ?></td>
                                <td><?php print $dados->getGrau(); ?></td>
                                <td><a href="#" id="remover" rel="<?php echo URL . "docente/remover/" . $dados->getPessoa()->getId(); ?>" ><i class="icon-trash"></i></a></td>
                                        <?php
                                    endforeach;
                                endif;
                                ?>

                </tbody>
            </table>
        </div>
    </div>
</div>



