<?php echo $this->menu; ?>
<div class=" " id="content" style="margin-left: 220px;">
    <!-- validation -->
    <div class="row-fluid">
        <!-- block -->
        <div class="block">
            <div class="col-12 pull-right">
                <h3>Acesso Rapido</h3>
                <div class="navbar">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo URL . "docente" . DS1 . "adicionar/" ?>"><span style="font-size: 14px; color: black;">Novo</span></a></li>
                        <li class="active"><a href="<?php echo URL . "docente" . DS1 . "editar/" ?>"><span style="font-size: 14px; color: black;">Editar</span></a></li>
                        <li class="active"><a href="<?php echo URL . "docente" . DS1 . "remover/" ?>"><span style="font-size: 14px; color: black;">Apagar</span></a></li>
                    </ul>
                </div>


            </div>

            <div style="position:absolute;
                 top: 250px;
                 left: 550px;">

                <select id="curso" >
                    <option value="">- Curso -</option>

                </select>
                <input type="button" name="btnPesquisar" value="Pesquisar" class="apagar"  onclick="getDados('apagar');"/>
                <input type="button" name="btnPesquisar" value="Carregar Todos" class="apagar"  onclick="getTodos('apagar');" />
                <input type="hidden" value="<?php echo URL; ?>public/img/6.gif" id="img"/>
            </div>
            <h3 style="position: absolute; right: 600px;">  <?php
                if (isset($this->titulo)): echo $this->titulo;
                endif;
                ?>
            </h3>
            <div id="conteudo">

            </div>

        </div>
    </div>
</div>



