<?php echo $this->menu; ?>
<?php

function selected($value, $selected) {
    return $value == $selected ? ' selected="selected"' : '';
}
?>
<div class="span10" id="content" style="margin-left: 250px;">
    <!-- validation -->
    <div class="row-fluid">
        <!-- block -->
        <div class="block">

            <div class="block-content collapse in">
                <div class="span8">
                    <!-- BEGIN FORM-->
                    <form action="<?php print URL; ?>modulo/editar" id="editar" class="form-horizontal" method="POST">
                        <fieldset>
                            <legend>Dados do Modúlo</legend>
                            <div class="form-group col-xs-12 col-sm-6 col-lg-7">
                                <label class="col-xs-4">Nome</label>
                                <div class="col-xs-12">
                                    <input type="text" name="nome"  class="form-control span9 borda" value="<?php print $this->dados->getNome(); ?>"/>
                                </div>
                            </div>
<!--                            <div class="control-group">
                                <label class="control-label">Curso<span class="required">*</span></label>
                                <div class="controls">
                                    <select class="span6 m-wrap" id="curso1" name="curso">
                                        <option value="CAP" <?php echo selected($this->dados->getCurso()->getNome(), "CAP") ?> >CAP</option>
                                        <option value="CEPAC" <?php echo selected($this->dados->getCurso()->getNome(), "CEPAC") ?>>CEPAC</option>
                                        <option value="CEPID" <?php echo selected($this->dados->getCurso()->getNome(), "CEPID") ?>>CEPID</option>
                                    </select>


                                </div>
                            </div>-->
                        </fieldset>

                        <input name="enviar" type="hidden" value="1"/>
                        <input name="id" type="hidden" value="<?php print $this->dados->getId(); ?>"/>
                       <div class="form-actions span10 text-center">
                            <button type="submit" class="btn btn-primary" id="editar">Alterar dados</button>
                            <button type="reset" class="btn btn-danger   active">Cancelar</button>
                        </div>
                        </fieldset>
                    </form>

                    <!-- END FORM-->
                </div>
            </div>
        </div>
        <!-- /block -->
    </div>
    <!-- /validation -->

</div>






























</form>
<!-- END FORM-->
</div>
</div>
</div>
<!-- /block -->
</div>
<!-- /validation -->

</div>
</div>