

<?php

use application\Session; ?>
<?php echo $this->menu; ?>
<div class="container">
    <!-- validation -->
    <div class="row-fluid">

        <div class="block-content collapse in">
            <div class="span12">
                <br />
                <div class="table-header">
                    Formulario de edição
                    <a href="<?php echo URL . "modulo"; ?>" style="color: white;"><span class="muted pull-right">Voltar ao menu</span></a>
                </div>
                <!-- BEGIN FORM-->

                <form action="<?php print URL; ?>modulo/editar" id="adicionar" class="form-horizontal" method="POST">
                    <legend>Dados do Modúlo</legend>

                    <fieldset>
                        <div class="form-group">

                            <label class="col-xs-2 control-label">Nome<span class="required">*</span></label>

                            <input type="text" name="nome"  class="form-control span4 borda" value="<?php print $this->dados->getNome(); ?> " />

                        </div>

                    </fieldset>

                    <input name="enviar" type="hidden" value="1"/>
                    <input name="id" type="hidden" value="<?php print $this->dados->getId(); ?>"/>
                    <div class="form-actions span10 text-center">
                        <button type="submit" class="btn btn-primary" id="adicionar">Salvar Dados</button>
                        <button type="reset" class="btn btn-danger   active">Cancelar</button>
                    </div>

                </form>

                <!-- END FORM-->
            </div>
        </div>
    </div>
    <!-- /block -->
</div>


