<?php

use application\Session; ?>
<?php echo $this->menu; ?>

<div class="hr hr-18 dotted hr-double"></div>

<div class="container-fluid">
    <!-- validation -->
    <div class="row">
        <div class="clearfix">
            <div class="pull-right tableTools-container">

            </div>
        </div>

        <div class="table-header">
            <?php
            if (isset($this->titulo)): echo $this->titulo;
            endif;
            ?>
            <a href="<?php echo URL . "modulo" . DS1 . "adicionar/" ?>" class="white pull-right">adicionar novo módulo<i class="fa fa-plus-circle"></i></a>
        </div>


        <table  class="table table-striped table-bordered table-responsive" id="tabela"> 
            <thead>
                <tr class="odd gradeA">

                    <th>CURSO</th>
                    <th>Descrição</th>
                    <th></th>

                </tr>
            </thead>

            <tbody>

                <?php if (isset($this->dados) && !empty($this->dados)): ?>
                    <?php foreach ($this->dados as $dados): ?>
                        <tr>
                            <td><?php print $dados->getNome(); ?></td>
                            <td><?php print $dados->getCurso()->getNome(); ?></td>
                            <td>
                                <div class="hidden-sm hidden-xs action-buttons">


                                    <a href="<?php echo URL . "modulo/editarDados/" . $dados->getId(); ?>" id="curso1" rel="<?php echo $dados->getId(); ?>">
                                        <span class="ace-icon fa fa-pencil bigger-130">

                                        </span>

                                    </a>
                                    <a href="#" class="red" id="remover" rel="<?php echo URL . "modulo" . DS1 . "remover/" . $dados->getId(); ?>">
                                        <span class="ace-icon fa fa-trash-o bigger-130">

                                        </span>
                                    </a>
                                </div>
                            </td>


                        </tr>

                        <?php
                    endforeach;
                endif;
                ?>

            </tbody>
        </table>
    </div>
</div>





