<?php

use application\Session; ?>
<?php echo $this->menu; ?>
<div class="container">
    <!-- validation -->
    <div class="row-fluid">

        <div class="block-content collapse in">
            <div class="span12">
                <br />
                <div class="table-header">
                    <?php
                    if (isset($this->titulo)): echo $this->titulo;
                    endif;
                    ?>
                    <a href="<?php echo URL . "modulo"; ?>" style="color: white;"><span class="muted pull-right">Voltar ao menu</span></a>
                </div>
                <!-- BEGIN FORM-->

                <form action="<?php print URL; ?>modulo/adicionar" id="adicionar" class="form-horizontal" method="POST">
                    <legend>Dados do Modúlo</legend>

                    <fieldset>
                        <div class="form-group">

                          <label class="col-xs-2 col-md-4 control-label">Nome<span class="required">*</span></label>

                            <input type="text" name="nome"  class="form-control span4 borda" value=" <?php
                            if (isset($this->dados) && !empty($this->dados)): echo $this->dados['nome'];
                            endif;
                            ?>"
                                   />

                        </div>

                        <div class="form-group"> 
                           <label class="col-xs-2 col-md-4 control-label">Curso<span class="required">*</span></label>
                            <select class="form-control span4 borda" id="curso" name="curso">
                                <option value="">-Selecciona um curso-</option>
                            </select>
                        </div>
                    </fieldset>

                    <input name="enviar" type="hidden" value="1"/>
                   <label class="col-md-5 col-xs-4 control-label" for="buscar"></label>
                        <button type="submit" class="btn btn-primary" id="adicionar">Salvar Dados</button>
                        <button type="reset" class="btn btn-danger   active">Cancelar</button>
                    </div>

                </form>

                <!-- END FORM-->
            </div>
        </div>
    </div>
    <!-- /block -->
</div>


