<?php use application\Session; ?>
<?php echo $this->menu; ?>



<div class="col-12 pull-left" style="position: absolute; top: -10px; left: 10px;">
    <h3></h3>
    <div class="navbar">
        <ul class="nav navbar-nav">
            <li class="active"><a href="<?php echo URL . "modulo" . DS1 . "index/" ?>" class="btn btn-primary"><span style="font-size: 14px; color: #FFFFFF;">Ver</span></a></li>
            <li class="active"><a href="<?php echo URL . "modulo" . DS1 . "editar/" ?>" class="btn btn-primary"><span style="font-size: 14px; color: #FFFFFF;">Editar</span></a></li>
            <?php if (strcmp(Session::get('nivel'), 'gestor') == 0): ?>
                <li class="active"><a href="<?php echo URL . "modulo" . DS1 . "remover/" ?>" class="btn btn-primary"><span style="font-size: 14px; color: #FFFFFF;">Apagar</span></a></li>
            <?php endif; ?>
        </ul>
    </div>


</div>



<div class="span10 " id="content" style="margin-left: 150px;">
    <!-- validation -->
    <div class="row-fluid">
        <!-- block -->
        <div class="block">

            <div class="navbar navbar-inner block-header" style="margin-top: 20px;">
                <div class="muted pull-right" style="padding: 10px; float: left; color: blue;">Dados do Curso</div>
            </div>
            <div class="block-content collapse in">
                <div class="span12">
                    <!-- BEGIN FORM-->
                    <form action="<?php print URL; ?>modulo/adicionar" id="adicionar" class="form-horizontal" method="POST">
                        <fieldset>
                            <legend>Dados do Modúlo</legend>
                            <div class="form-group col-xs-12 col-sm-6 col-lg-5">
                                <label class="col-xs-4">Nome</label>
                                <div class="col-xs-12">
                                    <input type="text" name="nome"  class="form-control span9 borda"/>
                                </div>
                            </div>
                            <div class="form-group col-xs-12 col-sm-6 col-lg-5">
                                <label class="col-xs-4">Curso</label>
                                <div class="col-xs-12">
                                    <select class="form-control span9 borda" id="curso" name="curso">
                                        <option value="">-Selecciona um curso-</option>
                                    </select>


                                </div>
                            </div>
                        </fieldset>

                        <input name="enviar" type="hidden" value="1"/>
                        <div class="form-actions span10 text-center">
                            <button type="submit" class="btn btn-primary" id="adicionar">Salvar Dados</button>
                            <button type="reset" class="btn btn-danger   active">Cancelar</button>
                        </div>

                    </form>

                    <!-- END FORM-->
                </div>
            </div>
        </div>
        <!-- /block -->
    </div>
    <!-- /validation -->

</div>






























</form>
<!-- END FORM-->
</div>
</div>
</div>
<!-- /block -->
</div>
<!-- /validation -->

</div>
</div>