<?php echo $this->menu; ?>
<div class="" id="content" style="margin-left: 220px;">
    <!-- validation -->
    <div class="row-fluid">
        <!-- block -->
        <div class="block">

            <table  class="table table-striped table-bordered">   
                <thead>
                    <tr class="odd gradeA">


                        <th>Nome</th>
                        <th>Curso</th>
                        <th>Apagar</th>

                    </tr>
                </thead>

                <tbody>

                    <?php if (isset($this->dados) && !empty($this->dados)): ?>
                        <?php foreach ($this->dados as $dados): ?>
                            <tr>

                                <td><?php print $dados->getNome(); ?></td>
                                <td><?php print $dados->getCurso()->getNome(); ?></td>
                                <td><a href="#" id="remover" rel="<?php echo URL . "modulo" . DS1 . "remover/" . $dados->getId(); ?>"><i class="icon-trash"></i></a></td>
                            </tr>

                            <?php
                        endforeach;
                    endif;
                    ?>

                </tbody>
            </table>
        </div>
    </div>
</div>










