
<?php echo $this->menu; ?>

<div class="hr hr-18 dotted hr-double"></div>

<div class="container-fluid">
    <!-- validation -->
    <div class="row">
        <div class="clearfix">
            <div class="pull-right tableTools-container">

            </div>
        </div>

        <div class="table-header">
            <?php
            if (isset($this->titulo)): echo $this->titulo;
            endif;
            ?>
               </div>


            <table  class="table table-striped table-bordered table-responsive" id="tabela">   
                <thead>
                    <tr class="odd gradeA">

                        <th>Nª BI</th> 
                        <th>Nome</th>
                        <th>CURSO</th>
                        <th>Ano de Conclusão</th>
                        <th></th>
                    </tr>
                </thead>

                <tbody>

                    <?php if (isset($this->dados) && !empty($this->dados)): ?>
                        <?php foreach ($this->dados as $dados): ?>
                            <tr>
                                <td><?php print $dados['bi']; ?></td>
                                <td><?php print $dados['nome']; ?></td>
                                <td><?php print $dados['n2']; ?></td>
                                <td><?php print date("d/m/Y", strtotime($dados['data'])); ?></td>
                                <td><a class="grey" target="__BLANK" href="<?php echo URL . "certificado" . DS1 . "gerar/" . $dados['aluno'] . '/' . $dados['modulo']; ?>"><span class="fa fa-print"></span></a></td>
                            </tr>

                            <?php
                        endforeach;
                    endif;
                    ?>

                </tbody>
            </table>
        </div>
    </div>


