
<div class="span10 " id="content" style="margin-left: 220px;">
    <!-- validation -->
    <div class="row-fluid">
        <!-- block -->
        <div class="block">

            <table  class="table table-striped table-bordered">   
                <thead>
                    <tr>

                        <th>CURSO</th> 
                        <th>MODÚLO</th>
                        <th>DOCENTE</th>
                        <th>NOME</th>
                        <th>DATA</th>

                    </tr>
                </thead>

                <tbody>

                    <?php if (isset($this->dados) && !empty($this->dados)): ?>
                        <?php foreach ($this->dados as $dados): ?>
                            <tr>
                                <td><?php print $dados->getCurso()->getNome(); ?></td>
                                <td><?php print $dados->getModulo()->getNome(); ?></td>
                                <td><?php print $dados->getDocente()->getPessoa()->getNome(); ?></td>
                                <td><?php print "{" . $dados->getNome() . "}"; ?><a href="<?php print URL . $dados->getNome(); ?>" target="_BLANK">     (VER)</a></td>
                                <td><?php print $dados->getData(); ?></td>
                            </tr>

                            <?php
                        endforeach;
                    endif;
                    ?>

                </tbody>
            </table>

        </div>
    </div>
</div>

