<?php

use application\Session; ?>
<?php echo $this->menu; ?>
<div class="hr hr-18 dotted hr-double"></div>

<div class="container">
    <!-- validation -->
    <div class="row">
        <div class="clearfix">
            <!--            <div class="pull-right tableTools-container">
            
                        </div>-->
        </div>

        <div class="table-header">
            <?php
            if (isset($this->titulo)): echo $this->titulo;
            endif;
            ?>
            <?php if (strcmp(Session::get('nivel'), 'docente') == 0): ?>

                <a href="<?php echo URL . "materia" . DS1 . "adicionar/" ?>" class="white pull-right">adicionar nova matéria<i class="fa fa-plus-circle"></i></a>
            <?php endif; ?>
        </div>


        <table  class="table table-striped table-bordered table-hover table-responsive" id="tabela">  
            <thead>
                <tr class="odd gradeA">

                    <th>CURSO</th> 
                    <th>MODÚLO</th>
                    <th>NOME</th>
                    <th>DATA</th>

                </tr>
            </thead>

            <tbody>

                <?php if (isset($this->dados) && !empty($this->dados)): ?>
                    <?php foreach ($this->dados as $dados): ?>
                        <tr>
                            <td><?php print $dados->getCurso()->getNome(); ?></td>
                            <td><?php print $dados->getModulo()->getNome(); ?></td>
                            <td><?php print "{" . $dados->getNome() . "}"; ?><a href="<?php print URL . $dados->getNome(); ?>" target="_BLANK">     (VER)</a></td>
                            <td><?php print $dados->getData(); ?></td>
                        </tr>

                        <?php
                    endforeach;
                endif;
                ?>

            </tbody>
        </table>
    </div>
</div>




