<?php

use application\Session; ?>
<?php echo $this->menu; ?>
<div class="container">
    <!-- validation -->
    <div class="row-fluid">

        <div class="block-content collapse in">
            <div class="span12">
                <br />
                <div class="table-header">
                    Formulario de cadastro
                    <a href="<?php echo URL . "materia"; ?>" style="color: white;"><span class="muted pull-right">Voltar a tabela</span></a>
                </div>
                <!-- BEGIN FORM-->
                <form action="<?php print URL; ?>materia/adicionar" class="form-horizontal" method="POST" accept-charset="utf-8" enctype="multipart/form-data" >
                    <fieldset>
                        <div class="form-group">

                            <label class="col-xs-2 col-md-4 control-label">Curso<span class="required">*</span></label>

                            <select class="form-control span4 m-wrap " id="curso" name="curso">
                                <option value=" ">-Selecciona um curso-</option>
                            </select>

                        </div>

                        <div class="form-group">
                            <label class="col-xs-2 col-md-4 control-label">Modúlo</label>

                            <select class="form-control span4 m-wrap" id="modulo" name="modulo">
                                <option value=" ">-Seleciona um modulo-</option>
                            </select>



                        </div>

                       


                        <<div class="form-group">
                           <label class="col-xs-2 col-md-4 control-label">Arquivo<span class="required">*</span></label>

                            <input type="file" name="arquivo" data-required="1" class="form-control span4 m-wrap"/>

                        </div>




                    </fieldset>

                    <input name="enviar" type="hidden" value="1"/>
                    <div class="form-actions span10 text-center">
                        <button type="submit" class="btn btn-primary" id="adicionar">Adicionar</button>
                        <button type="reset" class="btn btn-danger active">Cancelar</button>
                    </div>
                </form>
                <!-- END FORM-->
            </div>
        </div>
    </div>






