
<?php use application\Session; ?>

<?php
if(isset($this->mensagem) || isset($this->erro)): ?>
       
<div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container-fluid">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <?php if (Session::get('nivel') == "administrador"): ?>
                        <a class="brand" href="#">Painel de Administração</a>
                    <?php endif; ?>

                    <?php if (Session::get('nivel') == "docente"): ?>
                        <a class="brand" href="#">Painel de Docente</a>
                    <?php endif; ?>

                    <?php if (Session::get('nivel') == "aluno"): ?>
                        <a class="brand" href="#">Painel de Aluno</a>
                    <?php endif; ?>

                    <div class="nav-collapse collapse">
                        <ul class="nav pull-right">
                            <li class="dropdown">
                                <a href="#" role="button" class="dropdown-toggle" data-toggle="dropdown"> <i class="icon-user"></i> <?php print Session::get('nome'); ?> <i class="caret"></i>

                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a tabindex="-1" href="<?php echo URL . "matricula" . DS1 . "informacao/" . Session::get('id'); ?>">Perfil</a>
                                    </li>
                                    <li class="divider"></li>
                                    <li>
                                        <a tabindex="-1" href="<?php print URL ?>login/logof">Sair</a>
                                    </li>
                                </ul>
                            </li>
                        </ul>

                        <ul class="nav">
                            <?php if (Session::get('nivel') == "administrador"): ?>
                                <li class="active">
                                    <a href="<?php print URL ?>dashboard">Dashboard</a>
                                </li>
                            <?php endif; ?>

                            <?php if (Session::get('nivel') == "docente"): ?>
                                <li class="active">
                                    <a href="<?php print URL ?>dashboard/docente">Dashboard</a>
                                </li>
                            <?php endif; ?>

                            <?php if (Session::get('nivel') == "aluno"): ?>
                                <li class="active">
                                    <a href="<?php print URL ?>dashboard/aluno">Dashboard</a>
                                </li>
                            <?php endif; ?>


                            <?php if (isset($_layoutParam["menu"])): ?>
                                <?php for ($i = 0; $i < count($_layoutParam["menu"]); $i++): ?>
                                    <?php (($item && $_layoutParam["menu"][$i]["id"] == $item) ? $item_style = "corrent" : $item_style = ""); ?> 

                                    <li class="active" id="<?php print $item_style; ?>"><a href="<?php echo $_layoutParam["menu"][$i]["link"]; ?>"><i class="icon-chevron-right"></i> <?php echo $_layoutParam["menu"][$i]["titulo"]; ?></a></li>
                                    <?php
                                endfor;
                            endif;
                            ?>

                        </ul>
                    </div>
                </div>
            </div>
        </div>





<?php endif;
?>


<div class="span10 " id="content" style="margin-left: 200px;">
    <!-- validation -->
    <div class="row-fluid">
        <!-- block -->
        <div class="block">

            <div class="block-content collapse in">
                <div class="span12">
                    <!-- BEGIN FORM-->
                    <form action="<?php print URL; ?>materia/adicionar1" class="form-horizontal" method="POST" accept-charset="utf-8" enctype="multipart/form-data" >
                        <fieldset>
                            <legend class="text-info" style="margin-left: 200px;">Adicionar Nova Matéria de Formação</legend>

                            <div class="control-group">
                                <label class="control-label">Curso<span class="required">*</span></label>
                                <div class="controls">
                                    <select class="span6 m-wrap " id="curso" name="curso">
                                        <option value="000">-Selecciona um curso-</option>
                                    </select>


                                </div>
                            </div>

                            <div class="control-group">
                                <label class="control-label">Modúlo<span class="required">*</span></label>
                                <div class="controls">
                                    <select class="span6 m-wrap" id="modulo" name="modulo">
                                        <option value="000">-Seleciona um modulo-</option>
                                    </select>


                                </div>
                            </div>

                            <div class="control-group">
                                <label class="control-label">data<span class="required">*</span></label>
                                <div class="controls">
                                    <input type="text" id="data" data-provide="datepicker" name="data" data-required="1" class="span6 m-wrap"/>
                                </div>
                            </div>


                            <div class="control-group">
                                <label class="control-label">Arquivo<span class="required">*</span></label>
                                <div class="controls">
                                    <input type="file" name="arquivo" data-required="1" class="span6 m-wrap"/>
                                </div>
                            </div>




                        </fieldset>
                        <input name="docente" type="hidden" value="<?php ?>"/>
                        <input name="enviar" type="hidden" value="1"/>
                        <div class="form-actions">
                            <button type="submit" class="btn btn-primary" id="adicionar">Adicionar</button>
                            <button type="reset" class="btn">Cancelar</button>
                        </div>
                    </form>
                    <!-- END FORM-->
                </div>
            </div>
        </div>
        <!-- /block -->
    </div>
    <!-- /validation -->

</div>






