
<?php echo $this->menu; ?>

<?php if (strcmp(application\Session::get('nivel'), 'docente') == 0): ?>
    <div class="col-12 pull-left" style="position: absolute; top: -10px; left: 10px;">
        <h3></h3>
        <div class="navbar">
            <ul class="nav navbar-nav">
                <li class="active"><a href="<?php echo URL . "materia" . DS1 . "index/" ?>" class="btn btn-primary"><span style="font-size: 14px; color: #FFFFFF;">Lista</span></a></li>
                <li class="active"><a href="<?php echo URL . "materia" . DS1 . "adicionar1/" ?>" class="btn btn-primary"><span style="font-size: 14px; color: #FFFFFF;">Cadastrar</span></a></li>
                 
            </ul>
        </div>


    </div>
<?php endif; ?>
<div class="span10 " id="content" style="margin-left: 420px; margin-top: 50px;">
    <!-- validation -->
    <div class="row-fluid">
        <!-- block -->
        <div class="block">

            <div class="block-content collapse in">
                <div class="span12">
                    <!-- BEGIN FORM-->
                    <form action="<?php print URL; ?>materia/adicionar1" class="form-horizontal"id="adicionar" method="POST" accept-charset="utf-8" enctype="multipart/form-data" >
                        <fieldset>
                            <legend class="text-info text-center"><?php if(isset($this->sms) && !empty($this->sms)): echo $this->sms; endif;?></legend>

                            <div class="control-group">
                                <label class="control-label">Curso<span class="required">*</span></label>
                                <div class="controls">
                                    <select class="span6 m-wrap " id="curso" name="curso">
                                        <option value="">-Selecciona um curso-</option>
                                    </select>


                                </div>
                            </div>

                            <div class="control-group">
                                <label class="control-label">Modúlo<span class="required">*</span></label>
                                <div class="controls">
                                    <select class="span6 m-wrap" id="modulo" name="modulo">
                                        <option value="">-Seleciona um modulo-</option>
                                    </select>


                                </div>
                            </div>

                            <div class="control-group">
                                <label class="control-label">data<span class="required">*</span></label>
                                <div class="controls">
                                    <input type="text" id="data" data-provide="datepicker" name="data" data-required="1" class="span6 m-wrap"/>
                                </div>
                            </div>


                            <div class="control-group">
                                <label class="control-label">Arquivo<span class="required">*</span></label>
                                <div class="controls">
                                    <input type="file" name="arquivo" data-required="1" class="span6 m-wrap"/>
                                </div>
                            </div>




                        </fieldset>
                        <input name="docente" type="hidden" value="<?php ?>"/>
                        <input name="enviar" type="hidden" value="1"/>
                        <div class="form-actions">
                            <button type="submit" class="btn btn-primary" id="adicionar">Adicionar</button>
                            <button type="reset" class="btn">Cancelar</button>
                        </div>
                    </form>
                    <!-- END FORM-->
                </div>
            </div>
        </div>
        <!-- /block -->
    </div>
    <!-- /validation -->

</div>






