<?php echo $this->menu; ?>
<div id="content" style="margin-left: 120px;">
    <!-- validation -->
    <div class="row-fluid">
        <!-- block -->
        <div class="block">

            <table  class="table table-striped table-bordered" id="tabela">   
                <thead>
                     <tr class="odd gradeA">

                        <th>Nª BI</th> 
                        <th>Nome</th>
                        <th>CURSO</th>
                        <th>MODÚLO</th>
                         <th>IMPRIMIR</th>
                    </tr>
                </thead>

                <tbody>

                    <?php if (isset($this->dados) && !empty($this->dados)): ?>
                        <?php foreach ($this->dados as $dados): ?>
                            <tr>
                                <td><?php print $dados->getAluno()->getPessoa()->getBi(); ?></td>
                                <td><?php print $dados->getAluno()->getPessoa()->getNome(); ?></td>
                                <td><?php print $dados->getModulo()->getCurso()->getNome(); ?></td>
                                <td><?php print $dados->getModulo()->getNome(); ?></td>
                                <td><a target="__BLANK" href="<?php echo URL . "diploma" . DS1 . "gerar/" . $dados->getAluno()->getId(); ?>">DIPLOMA</a></td>
                            </tr>

                            <?php
                        endforeach;
                    endif;
                    ?>

                </tbody>
            </table>
        </div>
    </div>


