<?php echo $this->menu; ?>
<div id="content" style="margin-left: 15px;">
    <!-- validation -->
    <div class="row-fluid">
        <!-- block -->
        <div class="block">

            <div class="group-control" style="position: absolute; left: 420px; top: 220px;">
                <input type="number" name="ano" id="ano" data-required="1"  placeholder="Ano" maxlength="4"class=" form-control span7 m-wrap" />

                <select id="curso" class="form-control span5" >
                    <option value="">- Curso -</option>

                </select>
            </div>

        </div>

        <table  class="table table-striped table-bordered" id="tabela">   
            <thead>
                <tr class="odd gradeA">

                    <th>Nª BI</th> 
                    <th>Nome</th>
                    <th>CURSO</th>
                    <th>Ano de Conclusão</th>
                    <th>IMPRIMIR</th>
                </tr>
            </thead>

            <tbody>

                <?php if (isset($this->dados) && !empty($this->dados)): ?>
                    <?php foreach ($this->dados as $dados): ?>
                        <tr>
                            <td><?php print $dados['bi']; ?></td>
                            <td><?php print $dados['nome']; ?></td>
                            <td><?php print $dados['n2']; ?></td>
                            <td><?php print date("d/m/Y", strtotime($dados['data'])); ?></td>
                            <td><a target="__BLANK" href="<?php echo URL . "diploma" . DS1 . "gerar/" . $dados['aluno'] . '/' . $dados['modulo']; ?>">DIPLOMA</a></td>
                        </tr>

                        <?php
                    endforeach;
                endif;
                ?>

            </tbody>
        </table>
    </div>
</div>


