<?php

use application\Session; ?>
<?php echo $this->menu; ?>
<div class="container">
    <!-- validation -->
    <div class="row-fluid">

        <div class="block-content collapse in">
            <div class="span12">
                <br />
                <div class="table-header">
                Formulario
                    <a href="<?php echo URL . "generico/render/categoriaCientifica"; ?>" style="color: white;"><span class="muted pull-right">Voltar a tabela</span></a>
                </div>
                <!-- BEGIN FORM-->
                <form id="adicionar" class="form-horizontal" method="POST">
                    <fieldset>
                        <legend>Adicionar nova Categoria Cientifica</legend>

                        <div class="group-control">
                            <label class="col-xs-2 col-md-4 control-label">Nome<span class="required">*</span></label>
                            <input type="text" name="nome" data-required="1" class="form-control span4 m-wrap"/>
                        </div>
                    </fieldset>
                    <input name="enviar" type="hidden" value="1"/>
                    <input name="opcao" type="hidden" value="categoriaCientifica"/>
                    <label class="col-md-5 col-xs-4 control-label" for="buscar"></label>
                    <button type="submit" class="btn btn-primary" id="adicionar">Adicionar</button>
                    <button type="reset" class="btn btn-danger   active">Cancelar</button>
            </div>

            <!-- END FORM-->
            </form>
        </div>
    </div>
</div>
</div>
<!-- /block -->



