<?php

use application\Session; ?>
<?php echo $this->menu; ?>

<div class="hr hr-18 dotted hr-double"></div>

<div class="container">
    <!-- validation -->
    <div class="row">
        <div class="clearfix">
            <div class="pull-right tableTools-container">

            </div>
        </div>

        <div class="table-header">
            Tabela de funções cadastradas
            <a href="<?php echo URL . "generico" . DS1 . "adicionar/funcao" ?>" class="white pull-right">adicionar<i class="fa fa-plus-circle"></i></a>
        </div>


        <table  class="table table-striped table-bordered" id="tabela"> 
            <thead>
                <tr class="odd gradeA">
                    <th>Nome</th>
                    <th></th>

                </tr>
            </thead>

            <tbody>

                <?php if (isset($this->dados) && !empty($this->dados)): ?>
                    <?php foreach ($this->dados as $dados): ?>

                        <tr>
                            <td><?php print $dados->getNome(); ?></td>

                            <td>
                                <div class="hidden-sm hidden-xs action-buttons">


                                    <a rel="<?php print URL . "generico/editar/" . $dados->getId(); ?>/funcao" href="<?php print URL . "generico/editar/" . $dados->getId(); ?>/funcao">
                                        <span class="ace-icon fa fa-pencil bigger-130">

                                        </span>

                                    </a>
                                    <a href="<?php print URL . "generico/remover/" . $dados->getId(); ?>/funcao" id="remover" class="red">
                                        <span class="ace-icon fa fa-trash-o bigger-130">

                                        </span>
                                    </a>
                                </div>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        <?php else: ?>

        <?php endif; ?>

    </div>
</div>

