

<?php if (isset($this->dados) && !empty($this->dados)): ?>


<!--    <a  href="<?php echo URL . 'relatorio/' . 'imprimirAproveitamento'; ?>" target="_BLANK"><h4><i class="glyphicon glyphicon-print"></i>Imprimir</h4></a>-->
    
    <table class="table table-striped table-bordered" >
        <caption class="text-center"><h4> ESTATÍSTICA GERAL<br /><br /> NUMERO TOTAL DE NOTAS POR GENERO EM 2015<br />

            </h4>
        </caption>

        <tbody>


            <tr class="ro2"><td class="Default">
                     </td>
                <td rowspan="2" class="ce2"><strong>NOTAS </strong></td>
                <td colspan="2" class="ce5"><strong>GENÉRO</strong></td>
            </tr>
            <tr class="ro2">
                <td  class="Default"> 
                </td>
                <td class="ce5"><p>M</p></td><td style="text-align:left;width:2.258cm; " class="ce5"><p>F</p>
                </td>
                <td  class="ce5"><strong>TOTAL</strong>
                </td>
            </tr>
            <tr >

                <td> 
                <td><strong>EXCELENTE</strong></td><td><p><?php echo $this->dados['excelente_h']; ?></p></td>
                <td><p><?php echo $this->dados['excelente_m']; ?></p>
                </td>
                <td><p><?php echo $this->dados['total_ex']; ?></p>
                </td>
            </tr>

            <tr>
                <td> 
                </td>

                <td><strong>SUFICIENTE</strong></td>
                <td><p><?php echo $this->dados['suficiente_h']; ?></p>
                </td>
                <td><p><?php echo $this->dados['suficiente_m']; ?></p></td>
                <td><p><?php echo $this->dados['total_suf']; ?></p>
                </td>
                <td> 
                </td>
            </tr>
            <tr>
                <td class="Default"> 
                </td>


                <td class="ce3"><strong>BOM </strong>
                </td><td  class="ce3"><p><?php echo $this->dados['bom_m']; ?></p>
                </td><td  class="ce3"><p><?php echo $this->dados['bom_h']; ?></p>
                </td><td  class="ce5"><p><?php echo $this->dados['total_bom']; ?></p>
                </td>

            </tr>

        </tbody>
    </table>


<?php endif; ?>









<?php if (isset($this->aproveitamento) && !empty($this->aproveitamento)): ?>

<!--    <a  style="position: absolute; top: 400px;" href="<?php echo URL . 'relatorio/' . 'imprimirAproveitamentoPOrCurso/' . $this->aproveitamento['id']; ?>" target="_BLANK"><h4><i class="glyphicon glyphicon-print"></i>Imprimir</h4></a>-->
    <table class="table table-striped table-bordered">
        <caption class="text-center"><h4> Relatório Gerado pelo Sistema<br /><br /> NUMERO TOTAL DE NOTAS NO <?php echo $this->aproveitamento['id']; ?> EM 2015<br />

            </h4>
        </caption>

        <tbody>



            </tr>
            <tr class="ro2"><td class="Default">
                     </td>
                <td rowspan="2"  class="ce2"><strong>NOTAS </strong></td>
                <td colspan="2" class="ce5"><strong>GENÉRO</strong></td>
            </tr>
            <tr class="ro2">
                <td  class="Default"> 
                </td>
                <td class="ce5"><p>M</p></td><td style="text-align:left;width:2.258cm; " class="ce5"><p>F</p>
                </td>
                <td class="ce5"><strong>TOTAL</strong>
                </td>
            </tr>
            <tr>

                <td> 
                <td ><strong>EXCELENTE</strong></td><td><p><?php echo $this->aproveitamento['excelente_h_cap']; ?></p></td>
                <td ><p><?php echo $this->aproveitamento['excelente_m_cap']; ?></p>
                </td>
                <td><p><?php echo $this->aproveitamento['total_ex']; ?></p>
                </td>
            </tr>

            <tr >
                <td  class="Default"> 
                </td>

                <td ><strong>SUFICIENTE</strong></td>
                <td ><p><?php echo $this->aproveitamento['suficiente_h_cap']; ?></p>
                </td>
                <td ><p><?php echo $this->aproveitamento['suficiente_m_cap']; ?></p></td>
                <td ><p><?php echo $this->aproveitamento['total_suf']; ?></p>
                </td>
                <td > 
                </td>
            </tr>
            <tr >
                <td class="Default"> 
                </td>


                <td ><strong>BOM </strong>
                </td>
                <td ><p><?php echo $this->aproveitamento['bom_h_cap']; ?></p>
                </td>
                <td ><p><?php echo $this->aproveitamento['bom_m_cap']; ?></p>
                </td>
                <td ><p><?php echo $this->aproveitamento['total_bom']; ?></p>
                </td>


            <tr >
                <td  class="Default"> 
                </td>

                <td class="ce3"><strong>TOTAL </strong>
                </td><td class="ce3"><p><?php echo $this->aproveitamento['total_h']; ?></p>
                </td><td  class="ce3"><p><?php echo $this->aproveitamento['total_m']; ?></p>
                </td><td  class="ce5"><p><?php echo $this->aproveitamento['total_geral']; ?></p>
                </td>

        </tbody>
    </table>


<?php endif; ?>
