
<div class="span10 " id="content" style="margin-left: 180px;">
    <!-- validation -->
    <div class="row-fluid">
        <!-- block -->
        <div class="block">
          
            <div class="block-content collapse in">
                <div class="span12">
                    <!-- BEGIN FORM-->
                    <form action="<?php print URL; ?>relatorio/index1" id="buscar" class="form-horizontal" method="POST" >
                        <fieldset>
                            <legend class="text-info" style="margin-left: 180px;">Escolha uma das opções</legend>
                            <div class="control-group">
                                <label class="control-label">Opções<span class="required">*</span></label>
                                <div class="controls">
                                    <select class="span6 m-wrap " id="opcao" name="opcao">
                                        <option value="000">-Selecciona uma das opções-</option>
                                        <option value="geral">relatorio geral de aproveitamento dos alunos</option>
                                        <option value="CAP">relatorio geral de aproveitamento dos alunos no CAP</option>
                                        <option value="CEPAC">relatorio geral de aproveitamento dos alunos no CEPAC</option>
                                        <option value="CEPID">relatorio geral de aproveitamento dos alunos no CEPID</option>
                                    </select>


                                </div>
                            </div>

                        </fieldset>

                        <input name="enviar" type="hidden" value="1"/>
                        <div class="form-actions">
                            <button type="submit" class="btn btn-primary" id="buscar">Gerar</button>
                            <button type="reset" class="btn">Cancelar</button>
                        </div>
                    </form>
                    <!-- END FORM-->
                </div>
            </div>
        </div>
        <!-- /block -->
    </div>
    <!-- /validation -->

</div>




<br />

<?php if (isset($this->dados) && !empty($this->dados)): ?>



    <div class="span10 " id="content" style="margin-left: 300px;">
        <!-- validation -->
        <div class="row-fluid">
            <!-- block -->
            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left text-success">Dados Encontrados</div>
                </div>
                <div class="block-content collapse in">
                    <div class="span12">

                        <table  class="table table-striped table-bordered">   
                            <thead>
                                <tr>

                                    <th>Nome</th>
                                    <th>Nota</th>

                                </tr>
                            </thead>

                            <tbody>
                                <?php foreach ($this->dados as $dados): ?>
                                    <tr>
                                        <td><?php print $dados->getAluno()->getPessoa()->getNome(); ?></td>
                                        <td>            
                                            <form action="<?php print URL; ?>nota/adicionar"   method="POST">            
                                                <select  id="nota" name="nota">
                                                    <option>Seleccionar Nota...</option>
                                                    <option value="Excelente">Excelente</option>
                                                    <option value="Bom">Bom</option>
                                                    <option value="Suficiente">Suficiente</option>
                                                </select>
                                                <input type="hidden" name="aluno" value="<?php print $dados->getAluno()->getId(); ?>"/>
                                                <input type="hidden" name="curso" value="<?php print $dados->getCurso()->getId(); ?>"/>
                                                <input type="hidden" name="modulo" value="<?php print $dados->getModulo()->getId(); ?>"/>
                                                <input name="enviar" type="hidden" value="1"/>
                                                <input name="button" type="submit" class="input" id="button" value="Adicionar"/>
                                            </form>
                                        </td>
                                    </tr>

                                    <?php
                                endforeach;
                            endif;
                            ?>

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>




