<?php

use application\Session; ?>
<?php echo $this->menu; ?>

<div class="hr hr-18 dotted hr-double"></div>

<div class="container">
    <!-- validation -->
    <div class="row">

        <div class="block-content collapse in">
            <div class="span12">

                <div class="table-header">
                    <a href="<?php echo URL . "relatorio" . DS1 . " graficoGeral/" ?>" class="btn btn-primary"><span style="font-size: 14px; color: #FFFFFF;">Grafico</span></a>

                    <a href="<?php echo URL . "relatorio" . DS1 . "index/" ?>" class="btn btn-primary"><span style="font-size: 14px; color: #FFFFFF;">Por Matricula</span></a>     
                    <a href="<?php echo URL . "relatorio" . DS1 . "aproveitamentoGrafico/" ?>" class="btn btn-primary"><span style="font-size: 14px; color: #FFFFFF;">Por Aproveitamento</span></a>
                </div>
                <!-- BEGIN FORM-->
                <form action="<?php print URL; ?>relatorio/index" id="buscar" class="form-horizontal" method="POST" target="_BLANK">
                    <fieldset>
                        <legend class="text-info text-center">Escolha uma das opções</legend>
                        <div class="group-control">
                            <label class="col-xs-2 col-md-4 control-label">Opção<span class="required">*</span></label>
                            <select class="form-control span4 " id="opcao" name="opcao">
                                <option value="000">-Selecciona uma das opções-</option>
                                <option value="geral">relatorio geral de alunos matriculados</option>
                                <option value="CAP">relatorio geral de alunos matriculas no CAP</option>
                                <option value="CEPAC">relatorio geral de alunos matriculas no CEPAC</option>
                                <option value="CEPID">relatorio geral de alunos matriculas no CEPID</option>
                            </select>
                        </div>

                    </fieldset>

                    <input name="enviar" type="hidden" value="1"/>
                    <label class="col-md-5 col-xs-4 control-label" for="buscar"></label>
                    <button type="submit" class="btn btn-primary" id="buscar">Gerar</button>
                    <button type="reset" class="btn btn-danger active">Cancelar</button>
            </div>
            </form>
            <!-- END FORM-->


        </div>
    </div>
</div>
</div>


