


<?php if (isset($this->mt) && !empty($this->mt)): ?>
<!--    <a  href="<?php echo URL . 'relatorio/' . 'matriculadosImprimir/' ?>"  target="_BLANK"><h4><i class="glyphicon glyphicon-print"></i>Imprimir</h4></a>-->

    <table class="table table-striped table-bordered">
        <caption class="text-center"><h4> ESTATÍSTICA GERAL<br /><br /> TOTAL DE ALUNOS MATRICULADOS NO CEAFIE EM 2015<br />

            </h4>
        </caption>

        <tbody>



            <tr class="ro2"><td class="Default">
                     </td>
                <td rowspan="2"  class="ce2"><p>CURSO </p></td>
                <td colspan="2"  class="ce5"><p>GENERO</p></td>
            </tr>
            <tr class="ro2">
                <td  class="Default"> 
                </td>
                <td class="ce5"><p>M</p></td><td style="text-align:left;width:2.258cm; " class="ce5"><p>F</p>
                </td>
                <td  class="ce5"><p>TOTAL</p>
                </td>
            </tr>
            <tr >

                <td> 
                <td><p>CAP</p></td><td ><p><?php echo $this->mt['h_c']; ?></p></td>
                <td><p><?php echo $this->mt['m_c']; ?></p>
                </td>
                <td><p><?php echo $this->mt['total_cap']; ?></p>
                </td>
            </tr>

            <tr>
                <td class="Default"> 
                </td>

                <td><p>CEPAC</p></td>
                <td ><p><?php echo $this->mt['h_cepac']; ?></p>
                </td>
                <td><p><?php echo $this->mt['m_cepac']; ?></p></td>
                <td><p><?php echo $this->mt['total_cepac']; ?></p>
                </td>
                <td> 
                </td>
            </tr>
            <tr>
                <td class="Default"> 
                </td>


                <td><p>CEPID </p>
                </td><td  class="ce3"><p><?php echo $this->mt['h_cepid']; ?></p>
                </td><td class="ce3"><p><?php echo $this->mt['m_cepid']; ?></p>
                </td><td  class="ce5"><p><?php echo $this->mt['total_cepid']; ?></p>
                </td>

            <tr>
                <td class="Default"> 
                </td>

                <td  class="ce3"><p>TOTAL </p>
                </td><td class="ce3"><p><?php echo $this->mt['total_h']; ?></p>
                </td><td  class="ce3"><p><?php echo $this->mt['total_m']; ?></p>
                </td><td class="ce5"><p><?php echo $this->mt['total_geral']; ?></p>
                </td>
            </tr>
        </tbody>
    </table>

<?php endif; ?>











<?php if (isset($this->matricula) && !empty($this->matricula)): ?>
<!--    <a  href="<?php echo URL . 'relatorio/' . 'MatriculaPOrCursoImprimir/' . $this->matricula['curso']; ?>"  target="_BLANK"><h4><i class="glyphicon glyphicon-print"></i>Imprimir</h4></a>-->

    <table class="table">
        <caption class="text-center"><h4> Relatório Gerado pelo Sistema<br /><br /> TOTAL DE ALUNOS MATRICULADOS NO <?php echo $this->matricula['curso']; ?><br />

            </h4>
        </caption>

        <tbody>



            </tr>
            <tr class="ro2"><td  class="Default">
                     </td>
                <td rowspan="2"  class="ce2"><p>CURSO </p></td>
                <td colspan="2"  class="ce5"><p>GENERO</p></td>
            </tr>
            <tr class="ro2">
                <td  class="Default"> 
                </td>
                <td >
                    <p>M</p>
                </td>
                <td style="text-align:left;width:2.258cm; " >
                    <p>F</p>
                </td>
                <td><p>TOTAL</p>
                </td>
            </tr>
            <tr >

                <td></td>
                <td ><p><?php echo $this->matricula['curso']; ?></p></td>
                <td ><p><?php echo $this->matricula['h_c']; ?></p></td>
                <td ><p><?php echo $this->matricula['m_c']; ?></p>
                </td>
                <td ><p><?php echo $this->matricula['total']; ?></p>
                </td>
            </tr>


        </tbody>
    </table>
<?php endif; ?>





