<?php echo $this->menu; ?>
<div class=" " id="content" style="margin-left: 120px;">
    <!-- validation -->
    <div class="row-fluid">
        <!-- block -->
        <div class="block">

            <div class="col-12 pull-right">
                <h3>Acesso Rapido</h3>
                <div class="navbar">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo URL . "programa" . DS1 . "adicionar/" ?>"><span style="font-size: 14px; color: black;">Novo</span></a></li>
                        <li class="active"><a href="<?php echo URL . "programa" . DS1 . "editar/" ?>"><span style="font-size: 14px; color: black;">Editar</span></a></li>
                        <li class="active"><a href="<?php echo URL . "programa" . DS1 . "remover/" ?>"><span style="font-size: 14px; color: black;">Apagar</span></a></li>
                    </ul>
                </div>


            </div>
            <table  class="table table-striped table-bordered" id="tabela">   
                <thead>
                    <tr class="odd gradeA">

                        <th>CURSO</th> 
                        <th>MODÚLO</th>
                        <th>DOCENTE</th>
                        <th>LOCAL</th>
                        <th>INICIO</th>
                        <th>TERMINA</th>
                        <th>HORAS</th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>

                <tbody>

                    <?php if (isset($this->dados) && !empty($this->dados)): ?>
                        <?php foreach ($this->dados as $dados): ?>
                            <tr>
                                <td><?php print $dados->getCurso()->getNome(); ?></td>
                                <td><?php print $dados->getModulo()->getNome(); ?></td>
                                <td><?php print $dados->getDocente()->getPessoa()->getNome(); ?></td>
                                <td><?php print $dados->getLocal(); ?></td>
                                <td><?php print date("d/m/Y", strtotime($dados->getData())); ?></td>
                                <td><?php print date("d/m/Y", strtotime($dados->getDatafinal())); ?></td>
                                <td><?php print $dados->getHoras(); ?></td>
                                <td><a target="__BLANK" href="<?php echo URL . "programa" . DS1 . "gerar/" . $dados->getId(); ?>"><i class="icon icon-print"></i></a></td>
                                <td><a href="<?php echo URL . 'programa/editarDados/' . $dados->getId(); ?>"  rel="<?php echo $dados->getId(); ?>"><i class="icon-pencil"></i></a></td>

                            </tr>

                            <?php
                        endforeach;
                    endif;
                    ?>

                </tbody>
            </table>

        </div>
    </div>
</div>

