<?php

use application\Session; ?>
<?php echo $this->menu; ?>
<div class="hr hr-18 dotted hr-double"></div>

<div class="container-fluid">
    <!-- validation -->
    <div class="row">
        <div class="clearfix">
<!--            <div class="pull-right tableTools-container">

            </div>-->
        </div>

        <div class="table-header">
            <?php
            if (isset($this->titulo)): echo $this->titulo;
            endif;
            ?>
            <a href="<?php echo URL . "programa" . DS1 . "adicionar/" ?>" class="white pull-right">adicionar novo programa<i class="fa fa-plus-circle"></i></a>
        </div>


        <table  class="table table-striped table-bordered table-hover table-responsive" id="tabela">  
            <thead>
                <tr class="odd gradeA">

                    <th>CURSO</th> 
                    <th>MODÚLO</th>
                    <th>DOCENTE</th>
                    <th>LOCAL</th>
                    <th>INICIO</th>
                    <th>TERMINA</th>
                    <th></th>
                </tr>
            </thead>

            <tbody>

                <?php if (isset($this->dados) && !empty($this->dados)): ?>
                    <?php foreach ($this->dados as $dados): ?>
                        <tr>
                            <td><?php print $dados->getCurso()->getNome(); ?></td>
                            <td><?php print $dados->getModulo()->getNome(); ?></td>
                            <td><?php print $dados->getDocente()->getPessoa()->getNome(); ?></td>
                            <td><?php print $dados->getLocal(); ?></td>
                            <td><?php print $dados->getData(); ?></td>
                            <td><?php print $dados->getDatafinal(); ?></td>
                            <td>
                                <div class="hidden-sm hidden-xs action-buttons">
                                    <a target="__BLANK" href="<?php echo URL . "programa" . DS1 . "gerar/" . $dados->getId(); ?>" class="blue">
                                        <span class="ace-icon fa fa-print bigger-130">

                                        </span>
                                    </a>


                                    <a href="<?php echo URL . "programa/editarDados/" . $dados->getId(); ?>" id="editar1" rel="<?php echo $dados->getId(); ?>" class="green">
                                        <span class="ace-icon fa fa-pencil bigger-130">

                                        </span>
                                    </a>
                                    <a href="#" id="remover" rel="<?php echo URL . "programa" . DS1 . "remover/" . $dados->getId(); ?>" class="red">
                                        <span class="ace-icon fa fa-trash-o bigger-130">

                                        </span>
                                    </a>
                                </div>
                            </td>
                        </tr>

                        <?php
                    endforeach;
                endif;
                ?>

            </tbody>
        </table>

    </div>
</div>



