<?php use application\Session; ?>
<?php echo $this->menu; ?>


<div class="col-12 pull-left" style="position: absolute; top: -10px; left: 10px;">
    <div class="navbar">
        <h3></h3>
        <h3></h3>
        <ul class="nav navbar-nav">
            <li class="active"><a href="<?php echo URL . "programa" . DS1 . "adicionar/" ?>" class="btn btn-primary"><span style="font-size: 14px; color: #FFFFFF;">Adicionar</span></a></li>
            <li class="active"><a href="<?php echo URL . "programa" . DS1 . "editar/" ?>" class="btn btn-primary"><span style="font-size: 14px; color: #FFFFFF;">Editar</span></a></li>
            <?php if (strcmp(Session::get('nivel'), 'gestor') == 0): ?>
                <li class="active"><a href="<?php echo URL . "programa" . DS1 . "remover/" ?>" class="btn btn-primary"><span style="font-size: 14px; color: #FFFFFF;">Apagar</span></a></li>
            <?php endif; ?>
        </ul>
    </div>


</div>



<div  id="content" style="margin-left: 120px;">
    <table  class="table table-striped table-bordered table-responsive" id="tabela" cellspacing="0" width="100%">  
        <caption class="text-big text-center text-info">Tabela de programas cadastrados</caption>
        <thead>
            <tr class="odd gradeA">

                <th>CURSO</th> 
                <th>MODÚLO</th>
                <th>DOCENTE</th>
                <th>LOCAL</th>
                <th>INICIO</th>
                <th>TERMINA</th>
                
                <th></th>
            </tr>
        </thead>

        <tbody>

            <?php if (isset($this->dados) && !empty($this->dados)): ?>
                <?php foreach ($this->dados as $dados): ?>
                    <tr>
                        <td><?php print $dados->getCurso()->getNome(); ?></td>
                        <td><?php print $dados->getModulo()->getNome(); ?></td>
                        <td><?php print $dados->getDocente()->getPessoa()->getNome(); ?></td>
                        <td><?php print $dados->getLocal(); ?></td>
                        <td><?php print $dados->getData(); ?></td>
                        <td><?php print $dados->getDatafinal(); ?></td>
                        <td><a target="__BLANK" href="<?php echo URL . "programa" . DS1 . "gerar/" . $dados->getId(); ?>"><i class="icon icon-print"></i></a></td>

                    </tr>

                    <?php
                endforeach;
            endif;
            ?>

        </tbody>
    </table>

</div>


