<?php
echo $this->menu;

function selected($value, $selected) {
    return $value == $selected ? ' selected="selected"' : '';
}
?>

<div class="col-12 pull-left" style="position: absolute; top: -10px; left: 10px;">
    <h3></h3>
    <div class="navbar">
        <ul class="nav navbar-nav">
            <li class="active"><a href="<?php echo URL . "programa" . DS1 . "index/" ?>" class="btn btn-primary"><span style="font-size: 14px; color: #FFFFFF;">lista</span></a></li>
            <li class="active"><a href="<?php echo URL . "programa" . DS1 . "editar/" ?>" class="btn btn-primary"><span style="font-size: 14px; color: #FFFFFF;">Editar</span></a></li>
            <li class="active"><a href="<?php echo URL . "programa" . DS1 . "remover/" ?>" class="btn btn-primary"><span style="font-size: 14px; color: #FFFFFF;">Apagar</span></a></li>
        </ul>
    </div>


</div>

<div class="span9 " id="content" style="margin-left: 150px;">
    <!-- validation -->
    <div class="row-fluid">
        <!-- block -->
        <div class="block">


            <div class="navbar navbar-inner block-header" style="margin-top: 20px;">
                <div class="muted pull-right" style="padding: 10px; float: left; color: blue;">Dados do Programa</div>
            </div>
            <div class="block-content collapse in">
                <div class="span12">
                    <!-- BEGIN FORM-->
                    <form action="<?php print URL; ?>programa/adicionar" id="adicionar" method="POST" class="form form-horizontal" >


                        <legend class="text-info text-center">Adicionar Novo Programa de Formação</legend>
                        <fieldset>
                            <div class="form-group">

                                <label class="col-xs-2 control-label">Curso<span class="required">*</span></label>

                                <select class="form-control span6 m-wrap " id="curso" name="curso">
                                    <option value=" ">-Selecciona um curso-</option>
                                </select>

                            </div>
                            <div class="form-group">
                                <label class="col-xs-2 control-label">Modúlo</label>

                                <select class="form-control span6 m-wrap" id="modulo" name="modulo">
                                    <option value=" ">-Seleciona um modulo-</option>
                                </select>



                            </div>


                            <div class="form-group">

                                <label class="col-xs-2 control-label">Docente</label>

                                <select class="form-control span6 m-wrap" id="docente" name="docente">
                                    <option value=" ">-Seleciona o Docente-</option>
                                </select>

                            </div>


                            <div class="form-group">

                                <label class="col-xs-2 control-label">Local</label>

                                <input type="text" name="local"  class="form-control span6 m-wrap" value=" <?php
                                if (isset($this->dados) && !empty($this->dados)): echo $this->dados['local'];
                                endif;
                                ?>"/>

                            </div>


                            <div class="form-group">

                                <label class="col-xs-2 control-label">Inicio</label>
                                
                                    <input type="text" name="inicio" id="inicio" data-required="1" data-provide="datepicker" class="form-control span6 m-wrap"
                                           value=" <?php
                                           if (isset($this->dados) && !empty($this->dados)): echo $this->dados['inicio'];
                                           endif;
                                           ?>"/>
                              
                            </div>

                            <div class="form-group">
                                <label class="col-xs-2 control-label">Termino</label>
                                <input type="text" id="termino" name="termino" data-required="1" class="form-control span6 m-wrap" data-provide="datepicker"
                                       value=" <?php
                                       if (isset($this->dados) && !empty($this->dados)): echo $this->dados['termino'];
                                       endif;
                                       ?>"/>


                            </div>

                            <div class="form-group">

                                <label class="col-xs-2 control-label">Horas</label>
                                <select class="form-control span6 m-wrap"  name="hora" id="hora">
                                    <option value=" "  >-Seleciona-</option>
                                    <option value="20h" <?php
                                    if (isset($this->dados) && !empty($this->dados)): echo selected($this->dados['hora'], "20h");
                                    endif;
                                    ?>>-20h-</option>
                                    <option value="40h" <?php
                                    if (isset($this->dados) && !empty($this->dados)): echo selected($this->dados['hora'], "40h");
                                    endif;
                                    ?>>-40h-</option>
                                </select>
                            </div>

                        </fieldset>
                        <input name="enviar" type="hidden" value="1"/>
                        <div class="form-actions span10 text-center">
                            <button type="submit" class="btn btn-primary" id="adiciona">Adicionar</button>
                            <button type="reset" class="btn btn-danger   active">Cancelar</button>
                        </div>
                    </form>
                    <!-- END FORM-->
                </div>
            </div>
        </div>
    </div>
</div>
</div>

<!-- /block -->






