
<div class="span10 " id="content" style="margin-left: 250px;">
    <!-- validation -->
    <div class="row-fluid">
        <!-- block -->
        <div class="block">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-right"></div>
            </div>
            <div class="block-content collapse in">
                <div class="span12">
                    <!-- BEGIN FORM-->
                    <form action="<?php print URL; ?>programa/adicionar" id="adicionar" class="form-horizontal" method="POST" >
                        <fieldset>
                            <legend class="text-info text-center">Adicionar Novo Programa de Formação</legend>

                            <div class="control-group">
                                <label class="control-label">Curso<span class="required">*</span></label>
                                <div class="controls">
                                    <select class="span6 m-wrap " id="curso" name="curso">
                                        <option value="000">-Selecciona um curso-</option>
                                    </select>


                                </div>
                            </div>

                            <div class="control-group">
                                <label class="control-label">Modúlo<span class="required">*</span></label>
                                <div class="controls">
                                    <select class="span6 m-wrap" id="modulo" name="modulo">
                                        <option value="000">-Seleciona um modulo-</option>
                                    </select>


                                </div>
                            </div>

                            <div class="control-group">
                                <label class="control-label">Docente<span class="required">*</span></label>
                                <div class="controls">
                                    <select class="span6 m-wrap" id="docente" name="docente">
                                        <option value="000">-Seleciona o Docente-</option>
                                    </select>


                                </div>
                            </div>


                            <div class="control-group">
                                <label class="control-label">Local<span class="required">*</span></label>
                                <div class="controls">
                                    <input type="text" name="local" data-required="1" class="span6 m-wrap"/>
                                </div>
                            </div>

                            <div class="control-group">
                                <label class="control-label">Inicio<span class="required">*</span></label>
                                <div class="controls">
                                    <input type="date" id="inicio" data-provide="datepicker" name="inicio" data-required="1" class="span6 m-wrap"/>
                                </div>
                            </div>

                            <div class="control-group">
                                <label class="control-label">Termino<span class="required">*</span></label>
                                <div class="controls">
                                    <input type="date" id="termino" name="termino" data-required="1" class="span6 m-wrap" data-provide="datepicker"/>
                                </div>
                            </div>

                            <div class="control-group">
                                <label class="control-label">Horas<span class="required">*</span></label>
                                <div class="controls">
                                    <select class="span6 m-wrap"  name="hora">
                                        <option value="000">-Seleciona-</option>
                                        <option value="20h">-20h-</option>
                                        <option value="40h">-40h-</option>
                                    </select>


                                </div>
                            </div>



                        </fieldset>

                        <input name="enviar" type="hidden" value="1"/>
                        <div class="form-actions">
                            <button type="submit" class="btn btn-primary" id="adicionar">Adicionar</button>
                            <button type="reset" class="btn">Cancelar</button>
                        </div>
                    </form>
                    <!-- END FORM-->
                </div>
            </div>
        </div>
        <!-- /block -->
    </div>
    <!-- /validation -->

</div>






