

<table  class="table table-striped table-bordered" id="tabela" >   
    <thead>

        <tr class="odd gradeA">

            <th>Nª BI</th> 
            <th>Nome</th>
            <th>Ano de Matricula</th>
            <th>ESTADO</th>


        </tr>
    </thead>

    <tbody>

        <?php if (isset($this->dados) && !empty($this->dados)): ?>
            <?php foreach ($this->dados as $dados): ?>
                <tr> 
                    <td><?php print $dados['bi']; ?></td>
                    <td><a href="<?php echo URL . "matricula" . DS1 . "informacao/" . $dados['aluno']; ?>"><?php print $dados['nome']; ?></a></td>
                    <td><?php print date("Y", strtotime($dados['data'])); ?></td>
                    <?php if (strcmp($dados['estado'], "ABERTO") == 0): ?>
                        <td>
                            <a href="#" rel="<?php echo URL . "matricula" . DS1 . "editar/" . $dados['aluno']; ?>" id="validar">CONFIRMAR</a>
                        </td>

                    <?php else: ?>
                        <td>CONFIRMADO<a target="__BLANK" href="<?php echo URL . "matricula" . DS1 . "imprimir/" . $dados['id'] . '/' . $dados['data'] ?>">(Recibo)</a></td>
                    <?php endif; ?>

                </tr>

                <?php
            endforeach;
        else :
            ?>
        <td>Nenhum Registro encontrado</td>

    <?php
    endif;
    ?>

</tbody>
</table>


