<?php echo $this->menu;?>
<div class="" id="content" style="margin-left: 220px;">
    <!-- validation -->
    <div class="row-fluid">
        <!-- block -->
        <div class="block">
            <table  class="table table-striped table-bordered" id="tabela">   
                <thead>
                     <tr class="odd gradeA">

                        <th>Nª BI</th> 
                        <th>Nome</th>
                        <th>CURSO</th>
                        <th>MODÚLO</th>
                        <th>Editar</th>

                    </tr>
                </thead>

                <tbody>

                    <?php if (isset($this->dados) && !empty($this->dados)): ?>
                        <?php foreach ($this->dados as $dados): ?>
                            <tr>
                                <td><?php print $dados->getAluno()->getPessoa()->getBi(); ?></td>
                                <td><?php print $dados->getAluno()->getPessoa()->getNome(); ?></td>
                                <td><?php print $dados->getCurso()->getNome(); ?></td>
                                <td><?php print $dados->getModulo()->getNome(); ?></td>
                                <td><a href="<?php echo URL."matricula/editarDados/". $dados->getAluno()->getId(); ?>" id="editar1" rel="<?php echo $dados->getAluno()->getId(); ?>"><i class="icon-edit"></i></a></td>
                            </tr>
                                        <?php
                                    endforeach;
                                endif;
                                ?>

                </tbody>
            </table>
        </div>
    </div>
</div>



