<?php use application\Session; ?>
<?php $graduacao = $this->dados->getAluno()->getGraduacao(); ?>
<?php $unorganica = $this->dados->getAluno()->getUnidadeOrganica(); ?>
<?php $universidade = $this->dados->getAluno()->getUniversidade(); ?>
<?php $catDocente = $this->dados->getAluno()->getCategoriaDocente(); ?>
<?php $funcao = $this->dados->getAluno()->getFuncao(); ?>
<?php $cientifica = $this->dados->getAluno()->getCategoriaCientifica(); ?>


<style>

    .container {
        margin-top: 25px;
    }
    .form-inline .form-group > div.col-xs-8 {
        padding-left: 0;
        padding-right: 0;
    }
    .form-inline label {
        line-height: 34px;
    }
    .form-inline .form-control {
        width: 100%;
    }
    @media (min-width: 768px) {
        .form-inline .form-group {
            margin-bottom: 15px;
        }
    }

    .verifica{
        padding:3px;
        font-size:18px;
        border:3px #CCC solid;
    }

    .borda{
        border: 3px #CCC solid;
    }
    .texto{
        color: red;
        font-size: 13px;
    }

</style>
<script>
    $(document).ready(function () {
        alert('altera apenas o que for necessario');
        var graduacao = "<?php echo $graduacao; ?>";
        setTimeout(function () {
            $("#graduacao option:contains('" + graduacao + "')").attr('selected', true);
        }, 20);

        var universidade = "<?php echo $universidade; ?>";
        setTimeout(function () {
            $("#universidade option:contains('" + universidade + "')").attr('selected', true);
        }, 20);

        var unorganica = "<?php echo $unorganica; ?>";

        setTimeout(function () {
            $("#unidade_organica option:contains('" + unorganica + "')").attr('selected', true);
        }, 20);

        var catDocente = "<?php echo $catDocente; ?>";

        setTimeout(function () {
            $("#categoria_docente option:contains('" + catDocente + "')").attr('selected', true);
        }, 20);

        var funcao = "<?php echo $funcao; ?>";


        setTimeout(function () {
            $("#funcao option:contains('" + funcao + "')").attr('selected', true);
        }, 20);

        var cientifica = "<?php echo $cientifica; ?>";


        setTimeout(function () {
            $("#funcao option:contains('" + cientifica + "')").attr('selected', true);
        }, 20);


        // alert(variavel);

    });
</script>
<?php echo $this->menu; ?>
<?php

function selected($value, $selected) {
    return $value == $selected ? ' selected="selected"' : '';
}
?>

<div class="col-12 pull-left" style="position: absolute; top: -10px; left: 10px;">

    <h3></h3>
    <div class="navbar">
        <ul class="nav navbar-nav">
            <li class="active"><a href="<?php echo URL . "matricula" . DS1 . "index/" ?>" class="btn btn-primary"><span style="font-size: 14px; color:  #ffffff;" >Ver Formandos</span></a></li>
            <li class="active"><a href="<?php echo URL . "matricula" . DS1 . "editar/" ?>" class="btn btn-primary"><span style="font-size: 14px; color: #ffffff;">Editar</span></a></li>
            <?php if (strcmp(Session::get('nivel'), 'gestor') == 0): ?>
            <li class="active"><a href="<?php echo URL . "matricula" . DS1 . "remover/" ?>" class="btn btn-primary"><span style="font-size: 14px; color: #ffffff;">Apagar</span></a></li>
         <?php endif; ?>
        </ul>
    </div>


</div>



<div class="span12 " id="content" style="margin-left: 150px; ">
    <!-- validation -->
    <div class="row-fluid">
        <!-- block -->
        <br />
        <div class="block">
            <div class="navbar-nav container block-header" style="margin-top: 20px;">
                <div class="muted pull-right" style="padding: 10px; float: left; color: blue;">Dados do Formando</div>
            </div>
        </div>
        <div class="block-content collapse in">
            <div class="span12">
                <!-- BEGIN FORM-->
                <form  action="" id="edita" class="form form-inline form-multiple" method="POST" enctype="multipart/form-data" >
                    <fieldset>
                        <legend>Dados Pessoais</legend>
                        <?php if (isset($this->dados) && !empty($this->dados)): ?>



                            <div class="form-group col-xs-12 col-sm-6 col-lg-3">
                                <label class="col-xs-4">Nome</label>
                                <div class="col-xs-12">
                                    <input type="text" name="nome"  class="form-control span9 borda" value=" <?php print $this->dados->getAluno()->getPessoa()->getNome(); ?>"/>
                                </div>
                            </div>
                            <div class="form-group col-xs-12 col-sm-6 col-lg-3">

                                <label class="col-xs-4">Apelido</label>
                                <div class="col-xs-12">
                                    <input type="text" name="apelido" class="form-control span9 borda" value="<?php print $this->dados->getAluno()->getPessoa()->getApelido(); ?>"/>
                                </div>

                            </div>
                            <div class="form-group col-xs-12 col-sm-6 col-lg-3">
                                <label class="col-xs-4">Genero</label>
                                <div class="col-xs-12">
                                    <select class="form-control span9 borda" name="genero">
                                        <option value="masculino" <?php echo selected($this->dados->getAluno()->getPessoa()->getGenero(), "masculino") ?> >Masculino</option>
                                        <option value="femenino" <?php echo selected($this->dados->getAluno()->getPessoa()->getGenero(), "femenino") ?> >Femenino</option>
                                    </select>                                    
                                </div>
                            </div>
                        </fieldset>
                        <fieldset>
                            <p></p>
                            <div class="form-group col-xs-12 col-sm-6 col-lg-3">
                                <label class="col-xs-4">Nacionalidade</label>
                                <div class="col-xs-12">
                                    <select class="form-control span9" name="nacionalidade" id="nacionalidade">
                                        <option value="ANGOLANA" <?php echo selected($this->dados->getAluno()->getPessoa()->getNacionalidade(), "ANGOLANA") ?> >Angolana</option>
                                        <option value="Outro" <?php echo selected($this->dados->getAluno()->getPessoa()->getNacionalidade(), "Outro") ?> >Outro</option>

                                    </select>                   
                                </div>
                            </div>

                            <div class="group-control col-xs-12 col-sm-6 col-lg-3" id="bi">
                                <label class="col-xs-4">Nª Doc</label>
                                <div class="col-xs-12">
                                    <input name="bi" type="text" class="form-control span9" maxlength="14" value="<?php print $this->dados->getAluno()->getPessoa()->getBi(); ?>"/>
                                </div>
                            </div>




                            <div class="group-control col-xs-12 col-sm-6 col-lg-3">
                                <label class="col-xs-4">Telefone</label>
                                <div class="col-xs-12">
                                    <input name="telefone" type="tel" class="form-control span9 borda" maxlength="9" value="<?php
                                    echo $this->dados->getAluno()->getPessoa()->getTelefone();
                                    ?>"/> 
                                </div>
                            </div>

                            <div class="group-control col-xs-12 col-sm-6 col-lg-3">
                                <label class="col-xs-4">Email</label>
                                <div class="col-xs-12">
                                    <input name="email"  class="form-control span9 borda" type="email" value="<?php echo $this->dados->getAluno()->getPessoa()->getEmail(); ?>"/>
                                </div>
                            </div>

                        </fieldset>

                        <fieldset>
                            <legend>Dados Académicos</legend>
                            <div class="group-control col-xs-12 col-sm-6 col-lg-3">
                                <label class="col-xs-4">graduação</label>
                                <div class="col-xs-12">
                                    <select class="form-control span9 borda" name="graduacao" id="graduacao">


                                    </select>                   
                                </div>
                            </div>
                            <div class="group-control col-xs-12 col-sm-6 col-lg-3">
                                <label class="col-xs-4">Universidade</label>
                                <div class="col-xs-12">
                                    <select class="form-control span9 borda" name="universidade" id="universidade">

                                    </select>             
                                </div>
                            </div>
                        </fieldset>


                        <legend>Dados Profissionais</legend>

                        <fieldset>
                            <div class="group-control col-xs-12 col-sm-6 col-lg-3">
                                <label class="col-xs-8">Unidade Organica</label>
                                <div class="col-xs-12">
                                    <select class="form-control span9 borda" name="unidade_organica" id="unidade_organica">

                                    </select>
                                </div>
                            </div>
                            <div class="group-control col-xs-12 col-sm-6 col-lg-3">
                                <label class="col-xs-12">Categ Docente</label>
                                <div class="col-xs-12">
                                    <select class="form-control span9 borda" name="categoria_docente" id="categoria_docente">

                                    </select>
                                </div>
                            </div>
                        </fieldset>

                        <fieldset>
                            <div class="group-control col-xs-12 col-sm-6 col-lg-3">
                                <label class="col-xs-4">Função</label>
                                <div class="col-xs-12">
                                    <select class="form-control span9 borda" name="funcao" id="funcao">


                                    </select>
                                </div>
                            </div>
                            <div class="group-control col-xs-12 col-sm-6 col-lg-3">
                                <label class="col-xs-12">Categ Cientifica</label>
                                <div class="col-xs-12">
                                    <select class="form-control span9 borda" name="categoria_centifica" id="categoria_centifica">


                                    </select>                                    

                                </div>
                            </div>
                        </fieldset>




                        <br /><br />
                        <input name="enviar" type="hidden" value="1"/>

                        <div class="form-actions span10 text-center">
                            <button type="submit" class="btn btn-primary" id ="editas" >Salvar Dados</button>
                            <button type="reset" class="btn btn-danger   active">Cancelar</button>
                        </div>
                        <br /><br />

                    </form>
                    <?php
                endif;
                ?>
                <!-- END FORM-->
            </div>
        </div>
    </div>
    <!-- /block -->

    <!-- /block -->
</div>
<!-- /validation -->
