<?php echo $this->menu; ?>
<div class="" id="content" style="margin-left: 120px; " >
    <div class="row-fluid">
        <div class="block">
            <table  class="table table-striped table-bordered" id="tabela">   
                <thead>

                    <tr class="odd gradeA">
              
                <th>Nª BI</th> 
                <th>Nome</th>
                <th>CURSO</th>
                <th>MODÚLO</th>
                <th>Ano de Matricula</th>
                <th>ESTADO</th>

                </tr>
                </thead>

                <tbody>

                    <?php if (isset($this->dados) && !empty($this->dados)): ?>
                        <?php foreach ($this->dados as $dados): ?>
                            <tr>
                                <td><?php print $dados->getAluno()->getPessoa()->getBi(); ?></td>
                                <td><a href="<?php echo URL . "matricula" . DS1 . "informacao/" . $dados->getAluno()->getId(); ?>"><?php print $dados->getAluno()->getPessoa()->getNome(); ?></a></td>
                                <td><?php print $dados->getCurso()->getNome(); ?></td>
                                <td><?php print $dados->getModulo()->getNome(); ?></td>
                                <td><?php print $dados->getAno(); ?></td>
                                <?php if (strcmp($dados->getEstado(), "ABERTO") == 0): ?>
                                    <td>
                                        <!--------
                                        <div><img src="<?php //print URL                ?>public/img/8.gif" class="img-responsive" id="p"/></div>
                                    !---->
                                        <a href="#" rel="<?php echo URL . "matricula" . DS1 . "editar/" . $dados->getAluno()->getId(); ?>" id="validar">CONFIRMAR</a>
                                    </td>

                                <?php else: ?>
                                    <td>CONFIRMADO<a target="__BLANK" href="<?php echo URL . "matricula" . DS1 . "imprimir/" . $dados->getAluno()->getId(); ?>">(Recibo)</a></td>
                                <?php endif; ?>
                            </tr>

                            <?php
                        endforeach;
                    endif;
                    ?>

                </tbody>
            </table>
        </div>
    </div>
</div>



