<?php echo $this->menu; ?>


<div class="" id="content" style="margin-left: 120px; " >
    <div class="row-fluid">

        <div class="block">


            <div class="col-12 pull-right">

                <h3>Acesso Rapido</h3>
                <div class="navbar">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo URL . "matricula" . DS1 . "adicionar/" ?>"><span style="font-size: 14px; color: black;">Cadastrar</span></a></li>
                        <li class="active"><a href="<?php echo URL . "matricula" . DS1 . "editar/" ?>"><span style="font-size: 14px; color: black;">Editar</span></a></li>
                        <li class="active"><a href="<?php echo URL . "matricula" . DS1 . "remover/" ?>"><span style="font-size: 14px; color: black;">Apagar</span></a></li>
                    </ul>
                </div>


            </div>
            <div style="position:absolute;
                 top: 250px;
                 left: 550px;">

                <input type="number" name="ano" id="ano" data-required="1"  placeholder="Ano" maxlength="4"class="span2 m-wrap"/>
                <select id="curso" >
                    <option value="">- Curso -</option>

                </select>

                <select id="modulo1">
                    <option value="">- Modulo -</option>

                </select>
                <input type="button" name="btnPesquisar" value="Pesquisar" id="buscar"  onclick="getDados();" class="Pesquisar"/>
                <input type="button" name="btnPesquisar" value="Carregar Todos" id="buscar"  onclick="getTodos();" class="todos"/>
                <input type="hidden" value="<?php echo URL; ?>public/img/6.gif" id="img"/>

            </div>

            <div id="conteudo">

            </div>

        </div>

    </div>
</div>





