<?php

use application\Session; ?>
<?php echo $this->menu; ?>
<!--
<div class="col-xs-1 pull-left">


    <div>
        <h3></h3>
        <h3></h3>
        <ul class="nav navbar-nav">
            <li class="active"><a href="<?php echo URL . "matricula" . DS1 . "adicionar/" ?>" class="btn btn-primary"><span style="font-size: 14px; color:  #ffffff;" >Adicionar</span></a></li>
            <li class="active"><a href="<?php echo URL . "matricula" . DS1 . "editar/" ?>" class="btn btn-primary"><span style="font-size: 14px; color: #ffffff;">Editar</span></a></li>
<?php if (strcmp(Session::get('nivel'), 'gestor') == 0): ?>
                                                    <li class="active"><a href="<?php echo URL . "matricula" . DS1 . "remover/" ?>" class="btn btn-primary"><span style="font-size: 14px; color: #ffffff;">Apagar</span></a></li>
<?php endif; ?>
        </ul>
</div>
    </div>-->




<div class="container">



    <div class="row">
        <div class="col-xs-12">

            <!-- BEGIN FORM-->
    <!--        <form class="form form-horizontal" action="<?php print URL; ?>matricula/pesquisaPor/$" method="POST" target="_BLANK" >
                <fieldset>
                    <legend class="text-info text-center">Selecciona os dados a pesquisar</legend>
    
    
                    <div class="group-control">
                        <label class="control-label">Ano<span class="required">*</span></label>
                        <div class="controls">
                            <input type="text" name="ano" data-required="1" class="span6 m-wrap" id="ano"/>
    
                        </div>
                    </div>
                    <div class="group-control">
                        <label class="control-label">Curso<span class="required">*</span></label>
                        <div class="controls">
                            <select class="span6 m-wrap" id="curso" name="curso">
                                <option value="">-Selecciona um curso-</option>
                            </select>
    
    
                        </div>
                    </div>
    
                    <div class="group-control">
                        <label class="control-label">Modúlo<span class="required">*</span></label>
                        <div class="controls">
                            <select class="span6 m-wrap" id="modulo1" name="modulo1">
                                <option value="">-Seleciona um modulo-</option>
                            </select>
    
    
                        </div>
                    </div>
                </fieldset>
    
                <input name="enviar" type="hidden" value="1"/>
                <input name="acao" type="hidden" value="buscar"/>
                <div class="form-actions span12 text-center">
                    <button  name="pesquisa"  class="btn btn-success" value="pesquisar">Pesquisar</button>
                    <button  name="pesquisaT"  class="btn btn-primary"  >Carregar Todos</button>
                                            <input type="hidden" value="<?php echo URL; ?>public/img/6.gif" id="img"/>
                </div>
            </form>-->

            <!-- END FORM-->

            <form class="form-horizontal" action="<?php print URL; ?>matricula/pesquisaPor/$" method="POST" target="_BLANK">
                <fieldset>

                    <!-- Form Name -->
                    <legend>Seleciona os dados a pesquisar</legend>

                    <!-- Text input-->
                    <div class="form-group">
                        <label class="col-md-4 col-xs-4 control-label" for="ano">Ano</label>  
                        <div class="col-md-3 col-xs-3">
                            <input id="ano" name="ano" type="text" placeholder="Insira o ano" class="form-control input-md">

                        </div>
                    </div>

                    <!-- Select Basic -->
                    <div class="form-group">
                        <label class="col-md-4 col-xs-4 control-label" for="curso">Curso</label>
                        <div class="col-md-3 col-xs-3">
                            <select id="curso" name="curso" class="form-control">
                                <option value="1">Seleciona o curso</option>
                            </select>
                        </div>
                    </div>

                    <!-- Select Basic -->
                    <div class="form-group">
                        <label class="col-md-4 col-xs-4 control-label" for="modulo">Módulo</label>
                        <div class="col-md-3 col-xs-3">
                            <select id="modulo1" name="modulo1" class="form-control">
                                <option value="1">Seleciona o módulo</option>
                            </select>
                        </div>
                    </div>

                    <!-- Button (Double) -->
                    <div class="form-group">
                        <input name="enviar" type="hidden" value="1"/>
                        <input name="acao" type="hidden" value="buscar"/>
                        <label class="col-md-4 col-xs-4 control-label" for="buscar"></label>
                        <div class="col-md-3 col-xs-3">
                            <button id="buscar" name="buscar" class="btn btn-primary">Pesquisar</button>
                            <button id="todos" name="todos" class="btn btn-success">Carregar Todos</button>
                        </div>
                    </div>

                </fieldset>
            </form>


        </div>
    </div>
</div>









