






<?php echo $this->menu; ?>


<div class="container">
    <div class="row">

        <?php if (isset($this->dados) && !empty($this->dados)): ?>

            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad" >


                <div class="panel panel-info">
                    <div class="panel-heading">
                        <h3 class="panel-title"><?php echo ucfirst($this->dados->getAluno()->getPessoa()->getNome()) . ' ' . ucfirst($this->dados->getAluno()->getPessoa()->getApelido()); ?></h3>
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-3 col-lg-3 " align="center"> 
                                <?php if (!empty($this->dados->getAluno()->getPessoa()->getImagem())) : ?>
                                    <img alt="imagem" src="
                                         <?php print URL . $this->dados->getAluno()->getPessoa()->getImagem(); ?>" class="img img-circle img-responsive" />
                                     <?php else: ?>   
                                    <img src="<?php print URL; ?>public/img/10.jpg" class="img-responsive"/>

                                    <form id="guarda" method="POST" action="<?php print URL . "matricula/editarImagem/" . $this->dados->getAluno()->getPessoa()->getId() ?>" accept-charset="utf-8" enctype="multipart/form-data" class="form-horizontal">
                                        <input type="file" name="imagem" alt="xx"/>
                                        <input type="hidden" name="id" value="<?php echo $this->dados->getAluno()->getId(); ?>" />
                                        <button type="submit" id="guarda" class="btn btn-info">Guardar</button>
                                    </form>
                                <?php endif; ?>



                            </div>


                            <div class=" col-md-9 col-lg-9 "> 
                                <table class="table table-user-information">
                                    <tbody>
                                        <tr>
                                            <td>Nº do documento:</td>
                                            <td><?php echo $this->dados->getAluno()->getPessoa()->getBi(); ?></td>
                                        </tr>
                                        <tr>
                                            <td>Genero:</td>
                                            <td><?php echo ucfirst($this->dados->getAluno()->getPessoa()->getGenero()); ?></td>
                                        </tr>
                                        <tr>
                                            <td>Nacionalidade</td>
                                            <td><?php echo ucfirst($this->dados->getAluno()->getPessoa()->getNacionalidade()); ?></td>
                                        </tr>

                                        <tr>
                                        <tr>
                                            <td>Graduação</td>
                                            <td><?php echo $this->dados->getAluno()->getGraduacao(); ?></td>
                                        </tr>
                                        <tr>
                                            <td>Universidade</td>
                                            <td><?php echo $this->dados->getAluno()->getUniversidade(); ?></td>
                                        </tr>
                                        <tr>
                                            <td>Função</td>
                                            <td><?php echo $this->dados->getAluno()->getFuncao(); ?></td>
                                        </tr>

                                        <tr>
                                            <td>Categoria como docente</td>
                                            <td><?php echo $this->dados->getAluno()->getCategoriaDocente(); ?></td>
                                        </tr>
                                        <tr>
                                            <td>Unidade Organica</td>
                                            <td><?php echo $this->dados->getAluno()->getUnidadeOrganica(); ?></td>
                                        </tr>

                                        <tr>
                                            <td>Categoria Cientifica</td>
                                            <td><?php echo $this->dados->getAluno()->getCategoriaCientifica(); ?></td>
                                        </tr>

                                        <tr>
                                            <td>Email</td>
                                            <td><a href="mailto:<?php echo $this->dados->getAluno()->getPessoa()->getEmail(); ?>"><?php echo $this->dados->getAluno()->getPessoa()->getEmail(); ?></a></td>
                                        </tr>
                                    <td>Modulos inscrito</td>
                                    <?php foreach ($this->modulo as $valor): ?>
                                        <td>
                                            <br>
                                            <?php echo $valor->getModulo()->getNome(); ?>(<?php echo $valor->getModulo()->getCurso()->getNome(); ?>)
                                        </td>
                                    <?php endforeach; ?>

                                    </tr>

                                    </tbody>
                                </table>

                                <a href="<?php echo URL . "matricula" . DS1 . "addCurso/" . $this->dados->getAluno()->getId(); ?>" class="btn btn-primary">Inscrever em curso</i></a>
                                <a href="https://localhost/uan/matricula/pesquisaPor/$" class="btn btn-warning">Volta a lista</a>
                            </div>
                        </div>
                    </div>
                    <div class="panel-footer">
                        <a href="mailto:<?php echo $this->dados->getAluno()->getPessoa()->getEmail(); ?>" data-original-title="Enviar email" data-toggle="tooltip" type="button" class="btn btn-sm btn-primary"><i class="glyphicon glyphicon-envelope"></i></a>
                        <span class="pull-right">
                            <a href="<?php echo URL . "matricula/editarDados/" . $this->dados->getAluno()->getId() . "/" . $this->dados->getAluno()->getPessoa()->getId(); ?>" data-original-title="Editar este formando" data-toggle="tooltip" type="button" class="btn btn-sm btn-warning"><i class="glyphicon glyphicon-edit"></i></a>
                            <a id="remover" rel="<?php echo URL . "matricula" . DS1 . "remover/" . $this->dados->getAluno()->getPessoa()->getId(); ?>" data-original-title="Remove formando" data-toggle="tooltip" type="button" class="btn btn-sm btn-danger"><i class="glyphicon glyphicon-remove"></i></a>
                        </span>
                    </div>

                </div>
            </div>
        <?php else: ?>
            <span class="text-center">

                <h2>SEM INFORMAÇÕES PARA MOSTRAR</h2>

            </span> 

        <?php endif; ?>
    </div>
</div>

















