
<style>

    .container {
        margin-top: 25px;
    }
    .form-inline .form-group > div.col-xs-8 {
        padding-left: 0;
        padding-right: 0;
    }
    .form-inline label {
        line-height: 34px;
    }
    .form-inline .form-control {
        width: 100%;
    }
    @media (min-width: 768px) {
        .form-inline .form-group {
            margin-bottom: 15px;
        }
    }

    .verifica{
        padding:3px;
        font-size:18px;
        border:3px #CCC solid;
    }

    .borda{
        border: 3px #CCC solid;
    }
    .texto{
        color: red;
        font-size: 13px;
    }

</style>



<?php

function selected($value, $selected) {
    return $value == $selected ? ' selected="selected"' : '';
}
?>





<div class="col-12 pull-left" style="position: absolute; top: -10px; left: 10px;">

    <h3></h3>
    <div class="navbar">
        <ul class="nav navbar-nav">
            <li class="active"><a href="<?php echo URL . "login" ?>" class="btn btn-primary"><span style="font-size: 14px; color:  #ffffff;" >Acessar Conta</span></a></li>
        </ul>
    </div>


</div>




<div class="span12 " id="content" style="margin-left: 150px; ">
    <!-- validation -->
    <div class="row-fluid">
        <!-- block -->
        <br />
        <div class="block">
            <div class="navbar-nav container block-header" style="margin-top: 20px;">
                <div class="muted pull-right" style="padding: 10px; float: left; color: blue;">Dados do Formando</div>
            </div>
        </div>
        <div class="block-content collapse in">
            <div class="span12">
                <!-- BEGIN FORM-->
                <form action="<?php print URL; ?>matriculaonline/adicionar" id="adicionar" class="form form-inline"  method="POST"  >
                    <fieldset>
                        <legend>Dados Pessoais</legend>




                        <div class="form-group col-xs-12 col-sm-6 col-lg-3">
                            <label class="col-xs-4">Nome</label>
                            <div class="col-xs-12">
                                <input type="text" name="nome"  class="form-control span9 borda" value=" <?php
                                if (isset($this->dados) && !empty($this->dados)): echo $this->dados['nome'];
                                endif;
                                ?>"
                                       />
                            </div>
                        </div>
                        <div class="form-group col-xs-12 col-sm-6 col-lg-3">

                            <label class="col-xs-4">Apelido</label>
                            <div class="col-xs-12">
                                <input type="text" name="apelido"  class="form-control span9 borda" value="<?php
                                if (isset($this->dados) && !empty($this->dados)): echo $this->dados['apelido'];
                                endif;
                                ?>"/>
                            </div>

                        </div>
                        <div class="form-group col-xs-12 col-sm-6 col-lg-3">
                            <label class="col-xs-4">Genero</label>
                            <div class="col-xs-12">
                                <select class="form-control span9 borda" name="genero" id="genero">
                                    <option value="">-Seleciona um genero-</option>
                                    <option value="Masculino" <?php
                                    if (isset($this->dados) && !empty($this->dados)): echo selected($this->dados['genero'], "Masculino");
                                    endif;
                                    ?> >Masculino</option>
                                    <option value="Femenino" <?php
                                    if (isset($this->dados) && !empty($this->dados)): echo selected($this->dados['genero'], "Femenino");
                                    endif;
                                    ?> >Femenino</option>
                                </select>                                    
                            </div>
                        </div>
                    </fieldset>
                    <fieldset>
                        <p></p>
                        <div class="form-group col-xs-12 col-sm-6 col-lg-3">
                            <label class="col-xs-4">Nacionalidade</label>
                            <div class="col-xs-12">
                                <select class="form-control span9 borda" name="nacionalidade" id="nacionalidade">
                                    <option value="">-Seleciona a nacionalidade-</option>
                                    <option value="ANGOLANA" <?php
                                    if (isset($this->dados) && !empty($this->dados)): echo selected($this->dados['nacionalidade'], "ANGOLANA");
                                    endif;
                                    ?>>-Angola-</option>
                                    <option value="Outro" <?php
                                    if (isset($this->dados) && !empty($this->dados)): echo selected($this->dados['nacionalidade'], "Outro");
                                    endif;
                                    ?>>-Outro-</option>
                                </select>                   
                            </div>
                        </div>

                        <div class="group-control col-xs-12 col-sm-6 col-lg-3" id="bi">
                            <label class="col-xs-4">Nª Bi</label>
                            <div class="col-xs-12">
                                <input name="bi" id="bix" type="text" class="form-control span9 borda" maxlength="14" value="<?php
                                if (isset($this->dados) && !empty($this->dados)): echo $this->dados['bi'];
                                endif;
                                ?>"/>
                                <p class="texto" id="textobi"></p>

                            </div>
                        </div>

                        <div class="form-group col-xs-12 col-sm-6 col-lg-3" id="passaporte">
                            <label class="col-xs-4">Nª Doc</label>
                            <div class="col-xs-12">
                                <input name="passaporte" id="passportes" type="text" class="form-control span9 borda" maxlength="7" value="<?php
                                if (isset($this->dados) && !empty($this->dados)): echo $this->dados['passaporte'];
                                endif;
                                ?>"/>
                            </div>

                        </div>



                        <div class="group-control col-xs-12 col-sm-6 col-lg-3">
                            <label class="col-xs-4">Telefone</label>
                            <div class="col-xs-12">
                                <input name="telefone" id="telefone" type="text" class="form-control span9 verifica"  maxlength="9" value="<?php
                                if (isset($this->dados) && !empty($this->dados)): echo $this->dados['telefone'];
                                endif;
                                ?>"/> 
                                <p class="texto" id="textofone"></p>
                            </div>


                        </div>

                        <div class="group-control col-xs-12 col-sm-6 col-lg-3">
                            <label class="col-xs-4">Email</label>
                            <div class="col-xs-12">
                                <input name="email"  id="email" class="form-control span9 verifica" type="email" value="<?php
                                if (isset($this->dados) && !empty($this->dados)): echo $this->dados['email'];
                                endif;
                                ?>"/>
                                <p class="texto" id="textoemail"></p>

                            </div>

                        </div>

                    </fieldset>

                    <fieldset>
                        <legend>Dados Académicos</legend>
                        <div class="group-control col-xs-12 col-sm-6 col-lg-3">
                            <label class="col-xs-4">graduação</label>
                            <div class="col-xs-12">
                                <select class="form-control span9 borda" name="graduacao" id="graduacao">
                                    <option value="">-Seleciona a sua graduação-</option>

                                </select>                   
                            </div>
                        </div>
                        <div class="group-control col-xs-12 col-sm-6 col-lg-3">
                            <label class="col-xs-4">Universidade</label>
                            <div class="col-xs-12">
                                <select class="form-control span9 borda" name="universidade" id="universidade">
                                    <option value="">-Seleciona a sua universidade-</option>

                                </select>             
                            </div>
                        </div>
                    </fieldset>

                    <legend>Dados Profissionais</legend>

                    <fieldset>
                        <div class="group-control col-xs-12 col-sm-6 col-lg-3">
                            <label class="col-xs-8">Unidade Organica</label>
                            <div class="col-xs-12">
                                <select class="form-control span12 borda" name="unidade_organica" id="unidade_organica">
                                    <option value="">-Seleciona uma unidade organica</option>                                       

                                </select>
                            </div>
                        </div>
                        <div class="group-control col-xs-12 col-sm-6 col-lg-3">
                            <label class="col-xs-12">Categ Docente</label>
                            <div class="col-xs-12">
                                <select class="form-control span9 borda" name="categoria_docente" id="categoria_docente">
                                    <option value="">-Seleciona uma categoria</option>                                       

                                </select>
                            </div>
                        </div>
                    </fieldset>

                    <fieldset>
                        <div class="group-control col-xs-12 col-sm-6 col-lg-3">
                            <label class="col-xs-4">Função</label>
                            <div class="col-xs-12">
                                <select class="form-control span9 borda" name="funcao" id="funcao">
                                    <option value="">-Seleciona uma função-</option>


                                </select>
                            </div>
                        </div>
                        <div class="group-control col-xs-12 col-sm-6 col-lg-3">
                            <label class="col-xs-12">Categ Cientifica</label>
                            <div class="col-xs-12">
                                <select class="form-control span9 borda" name="categoria_centifica" id="categoria_centifica">
                                    <option value="">-Seleciona uma categoria-</option>


                                </select>                                    

                            </div>
                        </div>
                    </fieldset>


                    <fieldset>
                        <legend>Curso a frequentar</legend>
                        <div class="group-control col-xs-12 col-sm-6 col-lg-3">
                            <label class="col-xs-4">Curso</label>
                            <div class="col-xs-12">
                                <select class="form-control span9 borda" id="curso" name="curso">
                                    <option value="">Selecciona um curso</option>
                                </select>


                            </div>
                        </div>
                        <div class="carregando"></div>
                        <div class="group-control col-xs-12 col-sm-6 col-lg-3" id="modhide">
                            <label class="col-xs-4">Modúlo</label>
                            <div class="col-xs-12">
                                <select class="form-control span9 borda" id="modulo" name="modulo" >

                                </select>


                            </div>

                        </div>
                        <div class="group-control col-xs-12 col-sm-6 col-lg-3">
                            <label class="col-xs-4">Data</label>
                            <div class="col-xs-12">
                                <input type="text" name="data" class="form-control span9 borda" id="data" data-provide="datepicker" data-required="1" value="<?php
                                if (isset($this->dados) && !empty($this->dados)): echo $this->dados['data'];
                                endif;
                                ?>"/>

                            </div>
                        </div>
                    </fieldset>


                    <br /><br /><br /><br />
                    <input name="enviar" type="hidden" value="1"/>

                    <div class="form-actions span10 text-center">
                        <button type="submit" class="btn btn-primary" >Salvar Dados</button>
                        <button type="reset" class="btn btn-danger   active">Cancelar</button>
                    </div>
                    <br /><br />

                </form>

                <!-- END FORM-->
            </div>
        </div>
    </div>
    <!-- /block -->
</div>
<!-- /validation -->




