
<?php echo $this->menu; ?>
<?php

use application\Session ?>

<style>

    .container {
        margin-top: 25px;
    }
    .form-inline .form-group > div.col-xs-8 {
        padding-left: 0;
        padding-right: 0;
    }
    .form-inline label {
        line-height: 34px;
    }
    .form-inline .form-control {
        width: 100%;
    }
    @media (min-width: 768px) {
        .form-inline .form-group {
            margin-bottom: 15px;
        }
    }

    .verifica{
        padding:3px;
        font-size:18px;
        border:3px #CCC solid;
    }

    .borda{
        border: 3px #CCC solid;
    }
    .texto{
        color: red;
        font-size: 13px;
    }

</style>

<div class="container">
    <!-- validation -->
    <div class="row-fluid">

        <div class="block-content collapse in">
            <div class="span12">
                <div class="table-header">
                    <?php
                    if (isset($this->titulo)): echo $this->titulo;
                    endif;
                    ?>
                    <a href="<?php echo URL . "matricula"; ?>" style="color: white;"><span class="muted pull-right">Voltar ao menu</span></a>
                </div>
                <!-- BEGIN FORM-->
                <form action=""  class="form-horizontal" method="POST">

                    <legend>Curso a frequentar</legend>
                    <div class="form-group">
                        <label class="col-xs-2 control-label">Curso</label>

                        <select class="form-control span6 m-wrap borda" id="curso" name="curso">
                            <option value="">Selecciona um curso</option>
                        </select>
                    </div>
                    <div class="carregando"></div>
                    <div class="form-group">
                        <label class="col-xs-2 control-label">Modúlo<span class="required">*</span></label>
                        <select class="form-control  span6 m-wrap borda" id="modulo" name="modulo" >

                        </select>

                    </div>

                    <div class="form-group">
                        <label class="col-xs-2 control-label">Data de Inscrição<span class="required">*</span></label>
                        <input type="text" name="data" class=" form-control span6 m-wrap borda" id="data" data-provide="datepicker" data-required="1"/>
                    </div>


                    <input name="enviar" type="hidden" value="1"/>
                    <div class="form-actions span10 text-center">
                        <button type="submit" class="btn btn-primary" id="adicionar">Salvar Dados</button>
                        <button type="reset" class="btn btn-danger   active">Cancelar</button>
                    </div>


                </form>

                <!-- END FORM-->
            </div>
        </div>
    </div>
    <!-- /block -->
</div>

