<div class="hr hr-18 dotted hr-double"></div>

<div class="container-fluid">
    <!-- validation -->
    <div class="row">
        <div class="clearfix">
            <div class="pull-right tableTools-container">

            </div>
        </div>

        <div class="table-header">
            <?php
            if (isset($this->titulo)): echo $this->titulo;
            endif;
            ?>
            <a href="<?php echo URL . "matricula"; ?>" style="color: white;"><span class="muted pull-right">Voltar ao menu</span></a>
        </div>


        <table  class="table table-striped table-bordered table-hover table-responsive" id="tabela">   
            <thead>

                <tr class="odd gradeA">

                    <th>Nº BI/Passaporte</th> 
                    <th><i class="ace-icon fa fa-user bigger-110 hidden-480"></i>Nome</th>
                    <th><i class="ace-icon fa fa-times-circle-o bigger-110 hidden-480"></i>Ano de Matricula</th>
                    <th><i class="ace-icon fa fa-clock-o bigger-110 hidden-480"></i>Status</th>
                    <th></th>


                </tr>
            </thead>

            <tbody>

                <?php if (isset($this->dados) && !empty($this->dados)): ?>
                    <?php foreach ($this->dados as $dados): ?>
                        <tr> 
                            <td><?php print $dados['bi']; ?></td>
                            <td><?php print $dados['nome'] . ' ' . $dados['apelido']; ?></td>
                            <td><?php print date("Y", strtotime($dados['data'])); ?></td>
                            <?php if (strcmp($dados['estado'], "ABERTO") == 0): ?>
                                <td>
                                    <a href="#" rel="<?php echo URL . "matricula" . DS1 . "editar/" . $dados['aluno']; ?>" id="validar"><span class="label label-sm label-warning">confirmar</span>
                                    </a>
                                </td>

                            <?php else: ?>
                                <td>
                                    <span class="label label-sm label-success">confirmado</span>
                                    <a target="__BLANK" href="<?php echo URL . "matricula" . DS1 . "imprimir/" . $dados['id'] . '/' . $dados['data'] ?>"><i class="fa fa-print bigger-110 grey"></i></a></td>
                            <?php endif; ?>
                            <td>
                                <div class="hidden-sm hidden-xs action-buttons">

                                    <a class="blue" href="<?php print URL; ?>matricula/informacao/<?php echo $dados['aluno']; ?>">
                                        <i class="ace-icon fa fa-search-plus bigger-130"></i>
                                    </a>
                                    <a href="<?php echo URL . "matricula/editarDados/" . $dados['aluno'] . "/" . $dados['pessoa'] ?>" id="editar1" rel="<?php echo $dados['aluno']; ?>" class="green">
                                        <span class="ace-icon fa fa-pencil bigger-130">

                                        </span>
                                    </a>
                                    <a href="#" id="remover" rel="<?php echo URL . "matricula" . DS1 . "remover/" . $dados['pessoa']; ?>" class="red">
                                        <span class="ace-icon fa fa-trash-o bigger-130">

                                        </span>
                                    </a>
                                </div>
                            </td>



                        </tr>

                        <?php
                    endforeach;
                    ?>


                    <?php
                endif;
                ?>

            </tbody>
        </table>


    </div>
</div>