<?php

use application\Session; ?>
<?php echo $this->menu; ?>


<div class="hr hr-18 dotted hr-double"></div>

<div class="container-fluid">
    <!-- validation -->
    <div class="row">
        <div class="clearfix">
            <div class="pull-right tableTools-container">

            </div>
        </div>
        <div class="table-header">
            <?php
            if (isset($this->titulo)): echo $this->titulo;
            endif;
            ?>
            <a href="<?php echo URL . "usuario" . DS1 . "adicionar/" ?>" class="white pull-right">adicionar novo usuario<span class="fa fa-plus-circle"></span></a>
        </div>

        <table  class="table table-striped table-bordered table-hover table-responsive" id="tabela">   
            <thead>

                <tr class="odd gradeA">
                    <th ><i class="ace-icon fa fa-user bigger-110 hidden-480"></i>Nome</th> 
                    <th><i class="ace-icon fa fa-user-secret bigger-110 hidden-480"></i>Login</th>
                    <th><i class="ace-icon fa fa-star-half-empty bigger-110 hidden-480"></i>Nivel</th>
                    <th></th>

                </tr>
            </thead>

            <tbody>
                <?php if (isset($this->usuarios) && !empty($this->usuarios)): ?>
                    <?php foreach ($this->usuarios as $dados): ?>

                        <tr>
                            <td><?php print $dados->getPessoa()->getNome(); ?></td>
                            <td><?php print $dados->getLogin(); ?></td>
                            <td><?php print $dados->getNivel(); ?></td>
                            <td>

                                <div class="hidden-sm hidden-xs action-buttons">


                                    <a rel="<?php print URL . "usuario/editar/" . $dados->getId(); ?>" href="<?php print URL . "usuario/editar/" . $dados->getId(); ?>" id="usuario1" class="green">
                                        <span class="ace-icon fa fa-pencil bigger-130">

                                        </span>
                                    </a>
                                    <?php if (!strcmp($dados->getNivel(), 'aluno') == 0 || strcmp($dados->getNivel(), 'docente') == 0): ?>   
                                        <a rel="<?php print URL . "usuario" . DS1 . "remover" . DS1 . $dados->getPessoa()->getId(); ?>" href="<?php print URL . "usuario" . DS1 . "remover" . DS1 . $dados->getPessoa()->getId(); ?>" id="remover" class="red">
                                            <span class="ace-icon fa fa-trash-o bigger-130">

                                            </span>
                                        </a>
                                    <?php endif; ?>
                                </div>
                            </td>

                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        <?php else: ?>
            <h2 class="text-center text-error">Nenhum usuario cadastrado</h2>
        <?php endif; ?>
        <?php if (isset($this->paginacao) && !empty($this->paginacao)) //echo $this->paginacao;                 ?>
    </div>
</div>
