<?php

function selected($value, $selected) {
    return $value == $selected ? ' selected="selected"' : '';
}

use application\Session;
?>
<?php echo $this->menu; ?>


<div class="container">
    <!-- validation -->
    <div class="row-fluid">

        <div class="block-content collapse in">
            <div class="span12">
                <br />
                <div class="table-header">
                    Formulario de cadastro
                    <a href="<?php echo URL . "usuario"; ?>" style="color: white;"><span class="muted pull-right">Voltar ao menu</span></a>
                </div>
                <!-- BEGIN FORM-->



                <form action="<?php print URL; ?>usuario/index" id="adicionar" class="form-horizontal" method="POST" enctype="multipart/form-data">
                    <fieldset>
                        <legend>Dados do Usuario</legend>

                        <div class="form-group">
                           <label class="col-xs-2 col-md-4 control-label">Nome<span class="required">*</span></label>

                            <input type="text" name="nome" data-required="1" class="form-control span4 m-wrap"/>
                        </div>


                        <div class="form-group">
                            <label class="col-xs-2 col-md-4 control-label">Login<span class="required">*</span></label>

                            <input type="text" name="login" data-required="1" class="form-control span4 m-wrap"/>

                        </div>



                        <div class="form-group">
                            <label class="col-xs-2 col-md-4 control-label">Senha<span class="required">*</span></label>

                            <input type="password" name="senha" data-required="1" class="form-control span4 m-wrap"/>

                        </div>

                        <div class="form-group">

                            <label class="col-xs-2 col-md-4 control-label">Nivel<span class="required">*</span></label>

                            <select class="form-control span4 m-wrap" name="nivel">
                                <option value="">-Seleciona um nivel-</option>
                                <option value="administrador">administrador</option>
                                <option value="gestor">gestor</option>
                                <option value="funcionario">funcionario</option>
                            </select>                                    

                        </div>

                    </fieldset>
                    <input name="enviar" type="hidden" value="1"/>
                   <label class="col-md-5 col-xs-4 control-label" for="buscar"></label>
                        <button type="submit" class="btn btn-primary" id="adicionar">Salvar Dados</button>
                        <button type="reset" class="btn btn-danger   active">Cancelar</button>
                    </div>

                    <!-- END FORM-->
            </div>
        </div>
    </div>
    <!-- /block -->
</div>


