<?php echo $this->menu; ?>
<div class="span10 " id="content" style="margin-left: 150px;">
    <!-- validation -->
    <div class="row-fluid">
        <!-- block -->
        <div class="block">
            <div class="navbar navbar-inner block-header" style="margin-top: 20px;">
                <div class="muted pull-right"  style="padding: 10px; float: left; color: blue;">Dados do Aluno</div>
            </div>
            <div class="block-content collapse in">
                <div class="span12">
                    <!-- BEGIN FORM-->
                    <form action="<?php print URL; ?>usuario/index" id="adicionar" class="form-horizontal" method="POST" enctype="multipart/form-data">
                        <fieldset>
                            <legend>Dados do Usuario</legend>

                            <div class="form-group">
                                <label class="col-xs-2 control-label">Nome<span class="required">*</span></label>

                                <input type="text" name="nome" data-required="1" class="form-control span6 m-wrap"/>
                            </div>


                            <div class="form-group">
                                <label class="col-xs-2 control-label">Login<span class="required">*</span></label>

                                <input type="text" name="login" data-required="1" class="form-control span6 m-wrap"/>

                            </div>



                            <div class="form-group">
                                <label class="col-xs-2 control-label">Senha<span class="required">*</span></label>

                                <input type="password" name="senha" data-required="1" class="form-control span6 m-wrap"/>

                            </div>

                            <div class="form-group">

                                <label class="col-xs-2 control-label">Nivel<span class="required">*</span></label>

                                <select class="form-control span6 m-wrap" name="nivel">
                                    <option value="">-Seleciona um nivel-</option>
                                    <option value="administrador">administrador</option>
                                    <option value="gestor">gestor</option>
                                    <option value="funcionario">funcionario</option>
                                </select>                                    

                            </div>

                        </fieldset>
                        <input name="enviar" type="hidden" value="1"/>
                         <div class="form-actions span10 text-center">
                            <button type="submit" class="btn btn-primary" id="adicionar">Salvar Dados</button>
                            <button type="reset" class="btn btn-danger   active">Cancelar</button>
                        </div>

                        <!-- END FORM-->
                </div>
            </div>
        </div>
        <!-- /block -->
    </div>
    <!-- /validation -->

</div>






























</form>
<!-- END FORM-->
</div>
</div>
</div>
<!-- /block -->
</div>
<!-- /validation -->

</div>
</div>