



<?php

use application\Session; ?>
<?php echo $this->menu; ?>
<div class="container">
    <!-- validation -->
    <div class="row-fluid">

        <div class="block-content collapse in">
            <div class="span12">
                <br />
                <div class="table-header">
                    <?php
                    if (isset($this->titulo)): echo $this->titulo;
                    endif;
                    ?>
                    <a href="<?php echo URL . "curso"; ?>" style="color: white;"><span class="muted pull-right">Voltar ao menu</span></a>
                </div>
                <!-- BEGIN FORM-->

                <form  action="<?php print URL; ?>curso/editar" id="editar"  class="form-horizontal" method="POST" enctype="multipart/form-data">
                    <legend>Dados do Curso</legend>

                    <fieldset>


                        <div class="form-group">

                            <label class="col-xs-2 col-md-4 control-label">Nome<span class="required">*</span></label>

                            <input type="text" name="nome"  class="form-control span4 borda" value="<?php echo $this->dados->getNome(); ?>"
                                   />

                        </div>

                        <div class="form-group">

                            <label class="col-xs-2 col-md-4 control-label">Descrição<span class="required">*</span></label>
                            <textarea name="descricao"  class="form-control span4 borda">
                                <?php echo $this->dados->getDescricao(); ?>
                            </textarea>

                        </div>



                    </fieldset>

                    <input name="enviar" type="hidden" value="1"/>
                    <input name="id" type="hidden" value="<?php echo $this->dados->getId(); ?>"/>   
                    <label class="col-md-5 col-xs-4 control-label" for="buscar"></label>
                    <div class="col-md-4 col-xs-3">    <button type="submit" class="btn btn-primary" id="adicionar">Salvar Dados</button>
                    </div>

                </form>

                <!-- END FORM-->
            </div>
        </div>
    </div>
    <!-- /block -->
</div>




































</form>
<!-- END FORM-->
</div>
</div>
</div>
<!-- /block -->
</div>
<!-- /validation -->

</div>
</div>