<?php echo $this->menu; ?>
<div class="span10 " id="content" style="margin-left: 150px;">
    <!-- validation -->
    <div class="row-fluid">
        <!-- block -->
        <div class="block">
            <div class="navbar navbar-inner block-header" style="margin-top: 20px;">
                <div class="muted pull-right" style="padding: 10px; float: left; color: blue;">Dados do Aluno</div>
            </div>
            <div class="block-content collapse in">
                <div class="span12">
                    <!-- BEGIN FORM-->
                    <form action="<?php print URL; ?>curso/editar" id="editar" class="form-horizontal" method="POST">
                        <fieldset>
                            <legend>Dados do Curso</legend>
                            <div class="form-group col-xs-12 col-sm-6 col-lg-8">
                                <label class="col-xs-12">Nome</label>
                                <div class="col-xs-12">
                                    <input type="text" name="nome"  class="form-control span9 borda" value="<?php echo $this->dados->getNome(); ?>"/>
                                </div>
                            </div>
                            <div>
                                <label class="col-xs-12">Descrição</label>
                                <div class="col-xs-12">
                                    <textarea name="descricao"  class="form-control span9 borda"><?php echo $this->dados->getDescricao(); ?></textarea>
                                </div>
                            </div>
                        </fieldset>

                        <input name="enviar" type="hidden" value="1"/>
                        <input name="id" type="hidden" value="<?php echo $this->dados->getId(); ?>"/>   
                        <div class="form-actions span10 text-center">
                            <button type="submit" class="btn btn-primary" id="adicionar">Salvar Dados</button>
                            <button type="reset" class="btn btn-danger   active">Cancelar</button>
                        </div>
                        </fieldset>
                    </form>

                    <!-- END FORM-->
                </div>
            </div>
        </div>
        <!-- /block -->
    </div>
    <!-- /validation -->

</div>






























</form>
<!-- END FORM-->
</div>
</div>
</div>
<!-- /block -->
</div>
<!-- /validation -->

</div>
</div>