<?php echo $this->menu;?>
<div class="" id="content" style="margin-left: 420px;">
    <!-- validation -->
    <div class="row-fluid">
        <!-- block -->
        <div class="block">
            <table  class="table table-striped table-bordered" id="tabela">   
                <thead>
                      <tr class="odd gradeA">

                        <th>CURSO</th>
                        <th>Descrição</th>

                    </tr>
                </thead>

                <tbody>

                    <?php if (isset($this->dados) && !empty($this->dados)): ?>
                        <?php foreach ($this->dados as $dados): ?>
                            <tr>
                                <td><?php print $dados->getNome(); ?></td>
                                <td><?php print $dados->getDescricao(); ?></td>
                            </tr>

                            <?php
                        endforeach;
                    endif;
                    ?>

                </tbody>
            </table>
        </div>
    </div>
</div>



