<?php echo $this->menu; ?>


<div class="col-12 pull-right">
    <h3>Acesso Rapido</h3>
    <div class="navbar">
        <ul class="nav navbar-nav">
            <li class="active"><a href="<?php echo URL . "curso" . DS1 . "index/" ?>"><span style="font-size: 14px; color: black;">Ver Cursos</span></a></li>
            <li class="active"><a href="<?php echo URL . "curso" . DS1 . "editar/" ?>"><span style="font-size: 14px; color: black;">Editar</span></a></li>
            <li class="active"><a href="<?php echo URL . "curso" . DS1 . "remover/" ?>"><span style="font-size: 14px; color: black;">Apagar</span></a></li>
        </ul>
    </div>


</div>
<div class="span10 " id="content" style="margin-left: 420px;">
    <!-- validation -->
    <div class="row-fluid">
        <!-- block -->
        <div class="block">



            <div class="navbar navbar-inner block-header">
                <div class="muted pull-right">Dados do Curso</div>
            </div>
            <div class="block-content collapse in">
                <div class="span12">
                    <!-- BEGIN FORM-->
                    <form action="<?php print URL; ?>curso/adicionar" id="adicionar" class="form-horizontal" method="POST" enctype="multipart/form-data">
                        <fieldset>
                            <legend>Dados do Curso</legend>
                            <div class="control-group">
                                <label class="control-label">Nome<span class="required">*</span></label>
                                <div class="controls">
                                    <input type="text" name="nome" data-required="1" class="span6 m-wrap"/>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">Descrição<span class="required">*</span></label>
                                <div class="controls">
                                    <textarea name="descricao"  class="span6 m-wrap"></textarea>
                                </div>
                            </div>
                        </fieldset>

                        <input name="enviar" type="hidden" value="1"/>
                        <div class="form-actions">
                            <button type="submit" class="btn btn-primary" id="adicionar">Salvar Dados</button>
                            <button type="reset" class="btn">Cancelar</button>
                        </div>
                        </fieldset>
                    </form>

                    <!-- END FORM-->
                </div>
            </div>
        </div>
        <!-- /block -->
    </div>
    <!-- /validation -->

</div>






























</form>
<!-- END FORM-->
</div>
</div>
</div>
<!-- /block -->
</div>
<!-- /validation -->

</div>
</div>