<?php echo $this->menu; ?>
<div class=" " id="content" style="margin-left: 220px;">
    <!-- validation -->
    <div class="row-fluid">
        <!-- block -->
        <div class="block">


         
            <h3></h3>
            <div class="navbar">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="<?php echo URL . "curso" . DS1 . "adicionar/" ?>" class="btn btn-primary"><span style="font-size: 14px; color: #FFFFFF;">Adicionar</span></a></li>
                    <li class="active"><a href="<?php echo URL . "curso" . DS1 . "editar/" ?>" class="btn btn-primary"><span style="font-size: 14px; color: #FFFFFF;">Editar</span></a></li>
                    <li class="active"><a href="<?php echo URL . "curso" . DS1 . "index/" ?>" class="btn btn-primary"><span style="font-size: 14px; color: #FFFFFF;">Ver Cursos</span></a></li>
                </ul>
            </div>


        </div>

    </div>





    <table  class="table table-striped table-bordered" id="tabela">   
        <thead>
            <tr class="odd gradeA">

                <th>CURSO</th>
                <th>Descrição</th>
                <th>Apagar</th>

            </tr>
        </thead>

        <tbody>

            <?php if (isset($this->dados) && !empty($this->dados)): ?>
                <?php foreach ($this->dados as $dados): ?>
                    <tr>
                        <td><?php print $dados->getNome(); ?></td>
                        <td><?php print $dados->getDescricao(); ?></td>
                        <td><a href="#" id="remover" rel="<?php echo URL . "curso" . DS1 . "remover/" . $dados->getId(); ?>"><i class="icon-trash"></i></a></td>
                    </tr>

                    <?php
                endforeach;
            endif;
            ?>

        </tbody>
    </table>
</div>
</div>




