<br />
<table  class="table table-striped table-bordered">   
    <thead>
        <tr>

            <th>CURSO</th>
            <th>Descrição</th>

        </tr>
    </thead>

    <tbody>

        <?php if (isset($this->dados) && !empty($this->dados)): ?>
            <?php foreach ($this->dados as $dados): ?>
                <tr>
                    <td><?php print $dados->getNome(); ?></td>
                    <td><?php print $dados->getDescricao(); ?></td>
                    <td><a href="#" id="remover" rel="<?php echo URL . "curso" . DS1 . "remover/" . $dados->getId(); ?>"><i class="icon-trash"></i></a></td>
                </tr>

                <?php
            endforeach;
        endif;
        ?>

    </tbody>
</table>



